### PR TITLE
Implementing ``numpy.mod`` for array inputs

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lcompilers/lpython/issues/1035

### CODE REVIEW

**Comment by rebcabin** [comment]
Is numpy.mod defined for negative arguments? If so, are they tested here?

**Comment by czgdp1807** [comment]
From what I am able to figure out, `numpy.mod` doesn’t specify anything on sign of integers. Though its `numpy.fmod` which is supposed to work with negative integers. Plus `numpy.mod` is re-using Python’s `%` operator (which `numpy.mod` is supposed to do), so the behaviour will be equivalent and depend on how we define `%`. 
In any case, I will add a test for negative arrays and arrays with positives, negatives and 0s on Monday.

**Comment by czgdp1807** [comment]
> Is numpy.mod defined for negative arguments? If so, are they tested here?

Done.

**Review by certik — APPROVED** [review]
This looks good.

**Pull request merged**
