### PR TITLE
Use `LogicalToReal` cast kind directly

### PR DESCRIPTION
**Pull request by namannimmo10**

### CODE REVIEW

**Comment by czgdp1807** [comment]
I will review it tomorrow morning.

**Comment by namannimmo10** [comment]
Thanks for making the changes, @czgdp1807.

**Comment by namannimmo10** [comment]
@certik -- can you also take a look once?

**Comment by namannimmo10** [comment]
LFortran MR is merged, this can go in too.

**Comment by certik** [comment]
I think that this is fine.

**Pull request merged**
