### PR TITLE
Implement list.append

### PR DESCRIPTION
**Pull request by Smit-create**
#331

### CODE REVIEW

**Comment by certik** [comment]
Thanks. I think we should generate a new `ListAppend` ASR `stmt` node. Then implement it in the backend.

**Comment by certik** [comment]
Thanks. I think we should generate a new `ListAppend` ASR `stmt` node. Then implement it in the backend.

**Review by certik — APPROVED** [review]
Excellent. Looks really simple. Consistent with https://gitlab.com/lfortran/lfortran/-/merge_requests/1700.

**Comment by namannimmo10** [comment]
Thanks, @Smit-create ! I think we must also make sure that  ` l: list[i32];  l = [1, 2, 3];  l.append('a')` does not generate the ASR. See #365 .

**Pull request merged**
