### PR TITLE
[Parser] Implement parsing rules for functions

### PR DESCRIPTION
**Pull request by akshanshbhatt**
```
❯ cat examples/test_1.py
def main0():
    x: i32
    x = 5
    print(x)

❯ src/bin/lpython --show-ast --new-parser examples/test_1.py
syntax error: Token 'def' is unexpected here
 --> examples/test_1.py:1:1
  |
1 | def main0():
  | ^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

The new parser has not (yet) implemented the rules for function headers. I tried implementing it but got build errors -

```
❯ ./build0.sh
+ ci/version.sh
++ git describe --tags --dirty
+ version=v0.2.0-282-ga63bdc777-dirty
+ version=0.2.0-282-ga63bdc777-dirty
+ echo 0.2.0-282-ga63bdc777-dirty
+ python grammar/asdl_py.py
Assuming default values of Python.asdl and python_ast.py
+ python grammar/asdl_cpp.py grammar/Python.asdl src/lpython/python_ast.h
+ python grammar/asdl_cpp.py src/libasr/ASR.asdl src/libasr/asr.h
+ cd src/lpython/parser
+ re2c -W -b tokenizer.re -o tokenizer.cpp
+ cd src/lpython/parser
+ bison -Wall -d -r all parser.yy
parser.yy: error: shift/reduce conflicts: 1 found, 0 expected
```
or segmentation faults (in case it did compile) - 

```
❯ ./src/bin/lpython --show-ast --new-parser examples/expr2.py
Traceback (most recent call last):
  File "/Users/akshansh/Documents/GitHub/lpython/src/bin/lpython.cpp", line 752
    return emit_ast(arg_file, runtime_library_dir, compiler_options);
  File "/Users/akshansh/Documents/GitHub/lpython/src/bin/lpython.cpp", line 122
    al, runtime_library_dir, infile, diagnostics, compiler_options.new_parser);
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/parser/parser.cpp", line 95
    Result<LPython::AST::Module_t*> res = parse(al, input, diagnostics);
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/parser/parser.cpp", line 18
    Parser p(al, diagnostics);
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/parser/parser.cpp", line 51
    m_tokenizer.set_string(inp);
  File "parser.tab.cc", line 1726
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/python_ast.h", line 40
    LFORTRAN_ASSERT(is_a<T>(*f));
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803414c3
Segfault: Signal SIGSEGV (segmentation fault) received
```

For now, I have commented out the template code. @Thirumalai-Shaktivel, can you please guide me?

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Yup, Thanks @akshanshbhatt for showing your interest towards implementing `parser`.

**Comment by Thirumalai-Shaktivel** [comment]
```quote
❯ ./build0.sh
+ ci/version.sh
++ git describe --tags --dirty
+ version=v0.2.0-282-ga63bdc777-dirty
+ version=0.2.0-282-ga63bdc777-dirty
+ echo 0.2.0-282-ga63bdc777-dirty
+ python grammar/asdl_py.py
Assuming default values of Python.asdl and python_ast.py
+ python grammar/asdl_cpp.py grammar/Python.asdl src/lpython/python_ast.h
+ python grammar/asdl_cpp.py src/libasr/ASR.asdl src/libasr/asr.h
+ cd src/lpython/parser
+ re2c -W -b tokenizer.re -o tokenizer.cpp
+ cd src/lpython/parser
+ bison -Wall -d -r all parser.yy
parser.yy: error: shift/reduce conflicts: 1 found, 0 expected
```
Here at the last line, there is one grammatical conflict!
So, while defining the grammarl; make sure there are no conflicts.

**Comment by Thirumalai-Shaktivel** [comment]
```quote
❯ ./src/bin/lpython --show-ast --new-parser examples/expr2.py
Traceback (most recent call last):
  File "/Users/akshansh/Documents/GitHub/lpython/src/bin/lpython.cpp", line 752
    return emit_ast(arg_file, runtime_library_dir, compiler_options);
  File "/Users/akshansh/Documents/GitHub/lpython/src/bin/lpython.cpp", line 122
    al, runtime_library_dir, infile, diagnostics, compiler_options.new_parser);
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/parser/parser.cpp", line 95
    Result<LPython::AST::Module_t*> res = parse(al, input, diagnostics);
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/parser/parser.cpp", line 18
    Parser p(al, diagnostics);
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/parser/parser.cpp", line 51
    m_tokenizer.set_string(inp);
  File "parser.tab.cc", line 1726
  File "/Users/akshansh/Documents/GitHub/lpython/src/lpython/python_ast.h", line 40
    LFORTRAN_ASSERT(is_a<T>(*f));
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803414c3
Segfault: Signal SIGSEGV (segmentation fault) received
```
After defining the grammar, For ex:
```c++
function_def
    : KW_DEF id "(" arg_list ")" ":" statements {  }
```
if you get the above error, Then it is a success (Now the grammar defining part is complete)! 
Then we need to expose the Values to AST by defining the macros.

**Comment by Thirumalai-Shaktivel** [comment]
To get the tokens, you can do:
```console
$ lpython --show-tokens examples/expr2.py
(KEYWORD "def") 0:2
(TOKEN "identifier" main) 4:7
(TOKEN "(") 8:8
(TOKEN ")") 9:9
(TOKEN ":") 10:10
(NEWLINE) 11:11
(TOKEN "indent") 12:12
(TOKEN "identifier" print) 13:17
(TOKEN "(") 18:18
(TOKEN ")") 19:19
(NEWLINE) 20:20
(EOF) 21:21
```

**Comment by Thirumalai-Shaktivel** [comment]
For motivation please analyze: #349 #383

**Comment by Thirumalai-Shaktivel** [comment]
Hi @akshanshbhatt, function defintion is a little difficult to parse, why don't you try while or for statements

**Comment by Thirumalai-Shaktivel** [comment]
Here is the example program for while statement:
```python
i:i32 = 1
while i < 6:
    print(i)
    i += 1

i = 1
while i < 6:
    print(i)
    if i == 3:
        break
    i += 1

i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")

```

**Comment by Thirumalai-Shaktivel** [comment]
Grammar: https://docs.python.org/3/reference/compound_stmts.html#the-while-statement

**Comment by Thirumalai-Shaktivel** [comment]
@akshanshbhatt -- let us know, if you need any help with this PR.

**Comment by akshanshbhatt** [comment]
> @akshanshbhatt -- let us know if you need any help with this PR.

Sure, @Thirumalai-Shaktivel, I'll open a new PR. I've been a bit occupied lately with my end-semester examinations. I will complete this PR as soon as I get some time.

**Comment by Thirumalai-Shaktivel** [comment]
Sure, Take your time (also, All the best for your remaining exams)!

**Pull request closed without merging**
