### PR TITLE
Fix windows build failure

### PR DESCRIPTION
**Pull request by Smit-create**
See https://github.com/lcompilers/lpython/runs/5227998621?check_suite_focus=true

### CODE REVIEW

**Comment by Smit-create** [comment]
Tried 2-3 alternative solutions, but still fails!

**Comment by certik** [comment]
Thanks for trying! We'll have to figure out what is going on.

**Comment by certik** [comment]
I think you fixed it, now there is another issue.

**Comment by Smit-create** [comment]
Closing this in favour of #151

**Pull request closed without merging**
