### PR TITLE
Implement numpy.floor and numpy.ceil functions

### PR DESCRIPTION
**Pull request by Madhav2310**

### CODE REVIEW

**Comment by Madhav2310** [comment]
```
@overload
@vectorize
def floor(x: f32) -> f32:
    result: i32
    result = int(x)
    if x >= 0 or x == result:
        return float(result)
    return float(result - 1)
```
Since float returns f64, I tried other ways to return f32, but none seems to work. Please suggest how I can resolve it. @czgdp1807 @Smit-create

**Comment by Thirumalai-Shaktivel** [comment]
Try assigning the value to the variable of type `f32` and return the variable, Maybe that would work.

**Comment by Madhav2310** [comment]
> Try assigning the value to the variable of type `f32` and return the variable, Maybe that would work.

Thank you, that worked!

**Comment by Madhav2310** [comment]
@czgdp1807 @Smit-create Please review

**Comment by Smit-create** [comment]
> @Smit-create Would you mind completing this and get it merged?

Will do

**Review by czgdp1807 — APPROVED** [review]

**Pull request merged**
