### PR TITLE
[WASM_x86] Fix a bug that calculates the label_index in the Br visitor

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**
Fixes: #1298

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Thirumailai, it seems the condition `(loop_unique_id.size() + if_unique_id.size() - cur_nesting_length == label_index  + 1)` might not be simple to understand. I think there could be a simpler way if we try to simulate similar to how `wasm` does. `wasm` uses the same `label index space` for `if`'s and `loop`'s. Similary, if we use the same `label index space` for `if`'s and `loop`'s in `wasm->x86` backend, I think we can find a simpler approach. Ideally, we should attempt to follow the label indexing as described here https://github.com/lcompilers/lpython/pull/1290#discussion_r1020954737.

>`wasm` uses the same `label index space` for `if`'s and `loop`'s

By same `label index space`, I mean that `if` ids and `loop` ids would be counted from the same integer domain. That is, if there is an `if` with an `id = 4 (let's say)`, there could not be a `loop` with that same `id = 4`.

**Comment by Shaikh-Ubaid** [comment]
>(loop_unique_id.size() + if_unique_id.size() - cur_nesting_length) is same as nesting_level - cur_loop_nesting_level, right?

Yup, got it. I think the condition fine for the moment.

>Can you please share where the label index space is used in the wasm? or how it is implemented? (P.S. I didn't get it properly)

It is more abstract/conceptual. In simple words, what I mean by `wasm uses the same label index space for if's and loop's` is that `if`'s and `loop`'s use the same Id sequence (i.e. they take ids from the same set).

As the tests pass, let's merge this for the moment and we can improve upon it incrementally.

**Review by Shaikh-Ubaid — APPROVED** [review]
I tested it locally. It seems to work.

**Comment by Thirumalai-Shaktivel** [comment]
Before spilting into two id's (if_id, loop_id), I thought to use the same approach as wasm  does i.e., using nesting_level. Like push_back both loop_id and if_id into one stack. Later I realized it is difficult to retrieve the correct id's in the nested if_loop statement. 
Yup, this (`loop_unique_id.size() + if_unique_id.size() - cur_nesting_length`) seems to work for many cases. But, if you find any bug, do let me know or create an issue.
Thanks for the approval. Let's merge this.

**Comment by Shaikh-Ubaid** [comment]
> I thought to use the same approach as wasm does i.e., using nesting_level

Yes, I guessed. Since `wasm` already uses the nesting level and as we are working on `wasm` to `x86`, ideally, we should not be needing to use nesting level again (since it is something already figured out at the wasm level).

>ideally, we should not be needing to use nesting level again

I am not sure how much this ideal case is possible, but we need to try/experiment and see.

**Pull request merged**
