### PR TITLE
Sync ``libasr`` from LFortran

### PR DESCRIPTION
**Pull request by czgdp1807**
Corresponding LFortran PR - https://github.com/lfortran/lfortran/pull/705
Corresponding libasr PR - https://github.com/lcompilers/libasr/pull/4

### CODE REVIEW

**Comment by czgdp1807** [comment]
cc: @Thirumalai-Shaktivel @Shaikh-Ubaid @Smit-create @certik

**Review by Smit-create — APPROVED** [review]

**Review by Thirumalai-Shaktivel — APPROVED** [review]

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks good. Thank you.

**Comment by rebcabin** [comment]
I noticed that ASR.asdl has no entry for "SymbolTable," yet examples from LPython's test set has instances of "SymbolTable", e.g., https://github.com/lcompilers/lpython/blob/main/tests/reference/asr-expr_01-211000e.stdout .  I'm trying to write a clojure.spec that checks conformance of instances to specs, where specs are derived from the adsl (https://nextjournal.com/a/FnEMAE1Pkx2vWFMH6NVpJX/edit). But I don't know how to write a spec for "SymbolTable" because "SymbolTable" does not (apparently) appear in the ASR.adsl of this pull request.

**Comment by czgdp1807** [comment]
The stdout files are generated after picking the ASR. Here you can see the pickler, https://github.com/lcompilers/lpython/blob/main/src/lpython/pickle.cpp. Now `ASR::PickleBaseVisitor`'s code is generated. The portion you might be interested in is the following,

https://github.com/lcompilers/lpython/blob/84a073ce44a9a74213a4ac5648ee783bd38fc90f/src/libasr/asdl_cpp.py#L729-L734

Here's the generated code for `ASR::PickleBaseVisitor`,

<details>
<summary>Code for ASR::PickleBaseVisitor (click me to see the code)</summary>

```cpp
template <class Derived>
class PickleBaseVisitor : public BaseVisitor<Derived>
{
private:
    Derived& self() { return static_cast<Derived&>(*this); }
public:
    std::string s, indtd;
    bool use_colors;
    bool indent, start_line = true;
    int indent_level = 0, indent_spaces = 3, lvl = 0;
    int tmp = 0, tmp1 = 0, tmp2 = 2;
    int curly[2000], round[2000];
public:
    PickleBaseVisitor() : use_colors(false), indent(false) { s.reserve(100000); }
    void inc_indent() {
        indent_level++;
        indtd = std::string(indent_level*indent_spaces, ' ');
    }
    void dec_indent() {
        indent_level--;
        LFORTRAN_ASSERT(indent_level >= 0);
        indtd = std::string(indent_level*indent_spaces, ' ');
    }
    void visit_TranslationUnit(const TranslationUnit_t &x) {
        if(indent) {
            tmp1++;
            round[tmp1] = indent_level;
            if(start_line) {
                start_line = false;
                s.append(indtd);
                inc_indent();
            } else {
                s.append("\n"+indtd);
                inc_indent();
            }
        }
        s.append("(");
        if (use_colors) {
            s.append(color(style::bold));
            s.append(color(fg::magenta));
        }
        s.append("TranslationUnit");
        if (use_colors) {
            s.append(color(fg::reset));
            s.append(color(style::reset));
        }
        s.append(" ");
        if(indent) {
            s.append("\n"+indtd);
            round[++tmp1] = indent_level;
            inc_indent();
        }
        s.append("(");
        if (use_colors) {
            s.append(color(fg::yellow));
        }
        s.append("SymbolTable");
        if (use_colors) {
            s.append(color(fg::reset));
        }
        s.append(" ");
        if(indent) s.append("\n"+indtd);
        s.append(x.m_global_scope->get_counter());
        s.append(" ");
        if(indent) {
            s.append("\n"+indtd);
            curly[++tmp] = indent_level;
            tmp2 = 1;
            inc_indent();
        }
        s.append("{");
        {
            size_t i = 0;
            for (auto &a : x.m_global_scope->get_scope()) {
        if(indent) {
            s.append("\n"+indtd);
            inc_indent();
        }
              s.append(a.first + ": ");
                this->visit_symbol(*a.second);
                if (i < x.m_global_scope->get_scope().size()-1) { 
                    s.append(", ");
                    if(indent) {
                            for(int times = 0; times < tmp2; times++)
                             dec_indent();
                     }
                }
                i++;
            }
        }
        if(indent) {
            lvl = indent_level;
            for(int times = 0; times < (lvl - curly[tmp] ); times++)
                dec_indent();
            curly[tmp] = 0; if(tmp > 1) tmp--;
            tmp2++;
            s.append("\n"+indtd);
        }
        s.append("})");
        if(indent) dec_indent();
        s.append(" ");
        if(indent) s.append("\n"+indtd);
        s.append("[");
        for (size_t i=0; i<x.n_items; i++) {
            self().visit_asr(*x.m_items[i]);
            if (i < x.n_items-1) s.append(" ");
        }
        s.append("]");
        if(indent) {
            lvl = indent_level;
            for(int times = 0; times < (lvl - round[tmp1] ); times++)
                dec_indent();
            round[tmp1] = 0; if(tmp1 > 1) tmp1--;}
        s.append(")");
        if ((bool&)x) { } // Suppress unused warning
    }
```

To see the full code do `./build0.sh` and see `libasr/asr.h` file (search for `class PickleBaseVisitor` in the file).
</details>

**Comment by rebcabin** [comment]
> The stdout files are generated after picking the ASR. Here you can see the pickler, https://github.com/lcompilers/lpython/blob/main/src/lpython/pickle.cpp. Now `ASR::PickleBaseVisitor`'s code is generated. The portion you might be interested in is the following,
> 
> https://github.com/lcompilers/lpython/blob/84a073ce44a9a74213a4ac5648ee783bd38fc90f/src/libasr/asdl_cpp.py#L729-L734
> 
> Here's the generated code for `ASR::PickleBaseVisitor`,
> Code for ASR::PickleBaseVisitor (click me to see the code)

Is there a definition of "SymbolTable" in the ASR.asdl file? If so, which ASR.asdl file, because the one I pulled for branch "main" doesn't seem to have it.

If there is no definition of "SymbolTable" in the ASR.asdl fine, why not? Where is its formal definition? 

I want to generate tests for ASR processors. I need an ASDL file that has everything legal in ASR.

**Pull request merged**
