### PR TITLE
Fix issues with nested `dict`s

### PR DESCRIPTION
**Pull request by kabra1110**
Fixes issues to enable use of nested dictionaries.

### CODE REVIEW

**Comment by certik** [comment]
Thanks, great work. @czgdp1807 can you please review it?

**Review by czgdp1807 — APPROVED** [review]
So far it looks good to me.

**Comment by czgdp1807** [comment]
> This fix is important to ensure correct benchmarking of the changes in this PR.

How? This PR is related to `dict` and the issue you are talking about is `list`s.

**Comment by czgdp1807** [comment]
Got it. Let’s fix it in a subsequent PR.

**Pull request merged**
