### PR TITLE
better argument names for StringContains

### LINKED ISSUE #2786: ASR: bettern argument names for StringContains
Currently the ASDL definition is:
```
StringContains(expr left, expr right, ttype type, expr? value)
```
And we should rename `left` to `substr` and `right` to `str`.

### PR DESCRIPTION
**Pull request by Ayush-Devs**
This PR closes #2786 

Updated the StringContains ASDL definition:
expr left -> expr substr
expr right -> expr str

### CODE REVIEW

**Comment by certik** [comment]
@Ayush-Devs thank you! Do you mind also please submitting this same change to LFortran (https://github.com/lfortran/lfortran/) to ensure all tests pass there?

**Comment by Ayush-Devs** [comment]
Sorry, but I didnt quite understand what do you wanted me to do. I cloned LFortran on my system, only to find that
StringContains(expr left, expr right, ttype type, expr? value) is not present in its files.

What exactly do I have to do? A more brief answer would be helpful.
thank you

**Comment by certik** [comment]
@Ayush-Devs: we'll try to sync libasr from LFortran/LPython soon. Right now it's easier if you submit ASR changes via LFortran. If the StringContains is not there, then it either has to be added there, or removed from here.

**Comment by Ayush-Devs** [comment]
added StringContains in LFortran. i hope both the prs are ready to be merged. 

[https://github.com/lfortran/lfortran/pull/4723](url)

**Comment by certik** [comment]
Thanks!

**Pull request merged**
