### PR TITLE
fix: internal function def errors

### PR DESCRIPTION
**Pull request by arteevraina**
Towards: #2006

### CODE REVIEW

**Comment by certik** [comment]
Does get_symbol return a nullptr if it can't find the symbol?

**Comment by arteevraina** [comment]
> Does get_symbol return a nullptr if it can't find the symbol?

Yes, it returns ``nullptr`` when it can't find the symbol [here](https://github.com/lcompilers/lpython/blob/main/src/libasr/asr_scopes.h#L62).

The problem here is ``add_symbol`` function is only called for outer function and not for internal function definition. This I have verified by debugging in my local environment.

Also, for outer function definition `add_symbol` is being called after calling `make_Function_t_util` [here](https://github.com/lcompilers/lpython/blob/a18690b44b5b9ef78037d3eca3f69d3397fdc9d5/src/lpython/semantics/python_ast_to_asr.cpp#L4232-L4251). I am not sure why it is not doing the same for internal function definition as well.

I tried doing something like this :

```
if (t == nullptr) {
            old_scope->add_symbol(x.m_name, (ASR::symbol_t *) &x);
            visit_FunctionDef(x);
}
```

But, in the above case, `x->type` is getting as ``Program`` instead of ``Function``. That's why I think it's necessary to call ``make_Function_t_util`` for internal function definition as well.

**Review by certik — APPROVED** [review]
Ok, I think we can merge it, it's a better error message for sure.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
