### PR TITLE
Create main program properly

### PR DESCRIPTION
**Pull request by certik**
This creates a main program for the "main Python script" and includes any global commands in it (if any).

### CODE REVIEW

**Comment by certik** [comment]
Things to fix before merging:
* [ ] The C++ output seems to be skipping some stuff, investigate / fix
* [ ] Make all Python script call the "main" function, as you would in Python

**Comment by certik** [comment]
I noticed tests in `tests/expr12.py` are not present in the C++ output, not sure if this is caused by the "unused function optimization".

**Comment by certik** [comment]
The C++ tests didn't have a main program, so the functions were not called, thus the "unused" optimization optimized them out. This is now fixed and all the C++ tests now look good.

**Comment by certik** [comment]
Ok, this now allows us to write proper programs in LPython.

**Comment by namannimmo10** [comment]
Awesome, thanks for getting it done!!

**Pull request merged**
