### PR TITLE
Refactor string attributes and add constant string implementations

### PR DESCRIPTION
**Pull request by advikkabra**
- `istitle` and `isalpha` were implemented only for variables and not constant strings, so I added implementations and tests.
- Moved their tests to `test_str_attributes`along with all the other string methods.
- Removed some unnecessarycode in the python implementation of `istitle`
- Refactored the `istitle` and `isalpha` logic in `python_ast_to_asr.cpp` to follow the other `is` methods.

### CODE REVIEW

**Comment by certik** [comment]
Not sure what is going on, but somehow the CI shows an error:
```
semantic error: Variable 'x' not declared
   --> /home/runner/work/lpython/lpython/src/bin/../runtime/lpython_builtin.py:348:16
    |
348 |     return c64(x) + c64(0)*1j
    |                ^ 
```

**Comment by advikkabra** [comment]
I am not sure what is going on either, as there are no changes in `lpython_builtin.py` which should cause an error there. I will take a look again.

**Comment by advikkabra** [comment]
I tried building and running the tests locally, but I could not replicate the issue. I am using Ubuntu 22.04, so I am unsure why the CI is failing.

**Comment by advikkabra** [comment]
@certik Please take a look at this when you can, I am not sure how to fix this issue.

**Review by certik — APPROVED** [review]
I think this is fine. I don't know why it failed. We'll watch the CI for this error.

**Pull request merged**
