### PR TITLE
add arcsinh func

### PR DESCRIPTION
**Pull request by khushi-411**
Hi, all!
This is my first PR in lpython. I'm curious to learn more about compilers. Lpython looks like a great start. This PR adds the `arcsinh` function to the library.

Ref: #959

I look forward to contributing further and learning about compilers. Thanks!

cc'ing @certik @czgdp1807

### CODE REVIEW

**Comment by OmarMesqq** [comment]
Nice one, welcome! Is  `_lfortran_darcsinh()` implemented in the backend?

By the way, your CI build may be breaking due to different hashes. Run `./run_tests.py -u` and commit to your branch to update your build.

**Comment by khushi-411** [comment]
Hi, @OmarMesqq! Thanks for welcoming me and sharing insights on running tests :-)
Unfortunately, while checking further details, I found that `arcsinh` and some other functions are already implemented. Hence, closing this PR. I'll find some other exciting issues to work on! Please let me know if you'd like to share anything.

Thanks for your quick response!

**Comment by certik** [comment]
Hi @khushi-411, welcome. Thanks for the PR.

Yes, go ahead and find any bug or a feature that you want to fix. That would be awesome.

**Comment by khushi-411** [comment]
Hi @certik, Thanks for welcoming me!

Yes, I'm exploring areas where I can contribute and find interesting. I will submit a PR soon :-)

**Pull request closed without merging**
