### PR TITLE
Store initializer exprs for Structs in ASR

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
@certik This is an alternative approach to #2013 and I think this is more robust and doesn't create any confusion.

**Comment by certik** [comment]
I think that this is fine. Isn't it equivalent to store an iniitalizer in the Variable (inside a struct) or in the Struct?

**Comment by Smit-create** [comment]
> I think that this is fine. Isn't it equivalent to store an iniitalizer in the Variable (inside a struct) or in the Struct?

Yeah, that works. But it would require a lot of methods to be moved in CommonVisitor and may create problems of visiting them again in BodyVisitor which may affect the performance.

**Comment by Smit-create** [comment]
@certik This PR fixes all the issues related to #1981, and #2013. Moreover, also fixes the test in #2058.

**Review by czgdp1807 — APPROVED** [review]

**Pull request merged**
