### PR TITLE
WASM: Refactor

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This PR performs refactoring in the `wasm` backend to (hopefully) improve performance (and reduce code).

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
The commit [WASM: Remove unused memory debug functions](https://github.com/lcompilers/lpython/pull/1545/commits/b002f27008ffdc34e00c0e45daabdd35e0cf3461) could have been squashed/merged with its previous/parent commit. It is willingly kept separate so that later, if its need arises we can just revert it.

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please review and share feedback.

**Review by certik — APPROVED** [review]
I think that this is fine.

**Comment by Shaikh-Ubaid** [comment]
The latest two commits [WASM: Extract common code to declare_symbols()](https://github.com/lcompilers/lpython/pull/1545/commits/27236c05becf9f8a5eeed6c0e959b5658f0bf091), 
[WASM: Define and use import_function2()](https://github.com/lcompilers/lpython/pull/1545/commits/b2d57fae4b94a1939b2618f7ecc9f561ba113ac2) need review.

**Comment by Shaikh-Ubaid** [comment]
As this PR seems to be approved, I am adding it to auto-merge.

**Review by czgdp1807 — APPROVED** [review]
Please do the same re-factoring in LFortran's WASM as well. The tests should pass there as well for the same implementation here.

**Comment by certik** [comment]
The changes are fine with me.

**Comment by Shaikh-Ubaid** [comment]
>Please do the same re-factoring in LFortran's WASM as well. The tests should pass there as well for the same implementation here.

Absolutely, I would be happy to update the changes in LFortran's WASM as well. During my initial review, I had noted that some minor-changes were necessary in LFortran's WASM backend to align with the changes made here. I will ensure that the changes are implemented and that the tests pass successfully for both the lcompilers.

**Pull request merged**
