### PR TITLE
CI: make bash fail on errors

### LINKED ISSUE #2195: CI: Falsely passes
Reference: https://github.com/lcompilers/lpython/actions/runs/5607141184/jobs/10260627521

Thanks to @anutosh491 for pointing out that the CI tests were passing even after there is a failure. The job `LPython CI / Run SymPy tests (pull_request) ` should have failed in the current master, but it passes.

```
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/runner/work/lpython/lpython/integration_tests/_lpython-tmp-test-cpython_sym
Test project /home/runner/work/lpython/lpython/integration_tests/_lpython-tmp-test-cpython_sym
    Start 1: symbolics_01
    Start 2: symbolics_02
    Start 3: symbolics_03
    Start 4: symbolics_04
    Start 5: symbolics_05
    Start 6: symbolics_06
    Start 7: symbolics_07
1/7 Test #7: symbolics_07 .....................***Failed    0.20 sec
Traceback (most recent call last):
  File "/home/runner/work/lpython/lpython/integration_tests/symbolics_07.py", line 3, in <module>
    @ccall(header="symengine/cwrapper.h")
TypeError: ccall() got an unexpected keyword argument 'header'
```
```
86% tests passed, 1 tests failed out of 7

Label Time Summary:
c_sym          =   7.73 sec*proc (7 tests)
cpython_sym    =   7.73 sec*proc (7 tests)

Total Test time (real) =   1.33 sec

The following tests FAILED:
      7 - symbolics_07 (Failed)
```

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
Errors were ignored before.

fixes #2195

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
We need to rebase this PR after merging/completion of https://github.com/lcompilers/lpython/pull/2196.

**Comment by anutosh491** [comment]
> We need to rebase this PR after merging/completion of https://github.com/lcompilers/lpython/pull/2196.

Yes , otherwise the PR looks good . I can see we catch the errors which were being ignored prior to this !

**Comment by certik** [comment]
I think I did something similar for LFortran as well. Thanks for catching it!

**Comment by certik** [comment]
The SymPy test correctly failed (https://github.com/lcompilers/lpython/actions/runs/5608325831/job/15194656881?pr=2194), so let's see if it passes now.

**Review by anutosh491 — APPROVED** [review]
Looks good to me !

**Pull request merged**
