### PR TITLE
[New] Parse function call in the Subscription

### LINKED ISSUE #792: [New] Subscript for Function Call is not recognized
```py
$ lpython --show-ast examples/expr2.py --tree --new-parser
syntax error: Token '[' is unexpected here
 --> examples/expr2.py:1:22
  |
1 | return get_versions()["version"]
  |                      ^ 
```

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**
Closes #792

### CODE REVIEW

**Comment by akshanshbhatt** [comment]
```py
func()[1][1]
```

We should also add support for statements like this.

**Comment by Thirumalai-Shaktivel** [comment]
Thanks for the test. I parsed the Nested Subscript as well.

**Comment by certik** [comment]
The conflicts must be resolved.

**Review by certik — APPROVED** [review]
I think this is fine.

**Pull request merged**
