### PR TITLE
Add unsigned int types

### PR DESCRIPTION
**Pull request by Smit-create**
#1588

### CODE REVIEW

**Comment by Smit-create** [comment]
@certik Do you think we should move forward with these changes? I wanted your approval before making changes as it will include changes backend as well as some ASR.

**Review by certik — APPROVED** [review]
Yes, I think this is the minimal design that will get us there.

This should allow a relatively clean implementation that is separate from the integer implementation and should be easy to maintain. It does add some code everywhere, but it is maintainable for now, so I think we should start with this.

Thanks @Smit-create!

**Comment by certik** [comment]
This now prints 5:
```python
def main0():
    x: u32
    x = (u32(2)+u32(3))*u32(5)
    print(x)

main0()

# Not implemented yet in LPython:
#if __name__ == "__main__":
#    main()
```
The ASR is missing the arithmetic expression, it just has 5. But otherwise it seems to work. There are still many bugs and corner cases to get right.

**Comment by certik** [comment]
Now it works, just constants not generated.

**Comment by certik** [comment]
Constants work now. 

Thorough tests must be added.

**Comment by certik** [comment]
The added test does not work yet.

**Comment by certik** [comment]
The test works now.

We need to add many more tests, but the basics are working.

@czgdp1807 can you please review this? I'll polish the history tomorrow and merge.

**Review by czgdp1807 — APPROVED** [review]
Approving it but you might have noticed the type generation in LLVM. We need to clean it up and decouple it from ASRToLLVMVisitor. :-).

**Comment by certik** [comment]
Yes, it's all over the place, it's a mess. Ideally this is done at just once place, and all decisions shifted to physical types to ASR.

**Review by certik — APPROVED** [review]
This is good enough now to merge, I polished the commits.

More PRs will be needed with more tests, and fixing corner cases and Debug time wraparound tests.

**Comment by Smit-create** [comment]
Thanks, @certik for completing it!

**Pull request merged**
