### PR TITLE
WASM_X86: Support exit code

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
towards #1222

### CODE REVIEW

**Review by certik — APPROVED** [review]
Document (comment) what the function does (that it accepts the argument from the stack).

**Comment by Shaikh-Ubaid** [comment]
>Document (comment) what the function does (that it accepts the argument from the stack).

Yes, got it. I just added it in commit [WASM_X86: Add comments about emit_exit2() and X86Visitor stack working](https://github.com/lcompilers/lpython/pull/1285/commits/ad6c486eb02ade6e0eb8fc1ff13a32e96fa8f4a5).

**Comment by Shaikh-Ubaid** [comment]
There are some (supporting) tests activated/enabled for the `wasm_x86` backend in commit [TEST: WASM_X86: Enable supporting tests](https://github.com/lcompilers/lpython/pull/1285/commits/3c677110e966806426449103c39feb7571c721ca).

**Comment by Shaikh-Ubaid** [comment]
As this seems approved, I am adding this to `auto-merge`. (Hopefully, if the tests pass it would get merged).

**Pull request merged**
