### PR TITLE
Adding support for Structs inside Structs

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lcompilers/lpython/issues/700

### CODE REVIEW

**Comment by czgdp1807** [comment]
So the scene is a bit tricky here,

1. Fortran (i.e., concerned with LFortran) - By default, members which are of derived type are stored by value. Which means when you initialise say as `employee(jack, 2003)` where, `jack = person("Jack", "Smith")` then `jack` will be deep copied and hence, changes in `jack.fname` or any of its data members won't affect `employee.person.fname`.
2. Python (i.e., concerned with LPython) - By default, members which are of derived type are stored by reference. Taking the same example in point 1, now changes in `jack.fname` would be reflected in `employee.person.fname` and vice-versa.

Since, LLVM backend is common in both so either to store a derived type member of a struct by value or by reference should be somehow encoded in ASR while constructing it from input language's AST. For now, what I have done is, in LPython I wrap the derived type member in a Pointer type and rest of the code as is. So, in LLVM backend, the derived type members are pointers and hence effectively they get stored by reference and point 2 is satisfied.

cc: @certik

**Review by certik — APPROVED** [review]
I think that this is fine to go in.

Regarding value/reference, I would need to understand the details more. The options on the table are either

* keep ASR as is, and somehow support a subset of Python that maps to the current design
* modify ASR possibly as reference, and modify LFortran to use it, assuming it is a superset
* Add a flag to ASR Struct node, to choose which one it is

Ideally I am trying to keep the ASR simple and small, the smallest design that covers Fortran and the ahead of time compiled Python.

**Comment by czgdp1807** [comment]
Its the difference in semantics of Python and Fortran regarding derived types a.k.a classes which is the concern here. You can play around with the test in this PR and write something similar for Fortran, the differences will be clear.

**Comment by czgdp1807** [comment]
> Without knowing the details, it seems by value and no flag is the simplest/fastest, but if it can't be made to work with Python, then we need to improve the design.

As far as I can understand, do you mean that we should always deep copy. I think this won't give the expected behaviour in Python.

**Comment by certik** [comment]
It needs to behave like CPython. So either we give a compiler (or runtime) error, or it must behave like CPython.

I see, CPython is by reference. A simple solution is to never access the original variable (checked at compile time). Then it can be compiled by value.

**Comment by czgdp1807** [comment]
Well depends on how we fix, #691 . I will fix that first and then add this restriction.

**Pull request merged**
