### PR TITLE
[ASR Pass] Handle ArraySection and SIMDArray BinOp (LFortran Sync)

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by certik** [comment]
What is the status of this?

**Comment by Thirumalai-Shaktivel** [comment]
Ready

**Comment by certik** [comment]
This is fine, but let's merge the Fortran PR first.

**Review by certik — APPROVED** [review]

**Comment by Thirumalai-Shaktivel** [comment]
Thanks for the approval!

**Pull request merged**
