### PR TITLE
Initial Support for Global Dictionaries

### PR DESCRIPTION
**Pull request by harshsingh-24**
1. Solves #1593 
2. The support for Global Dictionary is needed for Implementing `Dictionary` return type to solve:  
#983 (specifically, ` Support passing dict as function arguments and return value of functions`)

@certik @czgdp1807 @Thirumalai-Shaktivel

### CODE REVIEW

**Comment by certik** [comment]
@Thirumalai-Shaktivel can you please review it?

**Review by czgdp1807 — APPROVED** [review]

**Review by Thirumalai-Shaktivel — APPROVED** [review]
LGTM!

**Comment by harshsingh-24** [comment]
Hey @Thirumalai-Shaktivel @czgdp1807 !! The C  backend currently does not support `str`. How can I make it support for `str`?

**Comment by certik** [comment]
Let's merge this after #1617.

**Pull request merged**
