### PR TITLE
Enabling c backend for test_c_interop_03.py

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/lcompilers/lpython/issues/545#issuecomment-1153482908 (2nd point)

### CODE REVIEW

**Comment by certik** [comment]
Excellent, thanks for this. After this works for all the other types as well, so we do not need to modify the test, then we can merge it.

**Comment by czgdp1807** [comment]
Yes. Will continue this tomorrow morning.

**Comment by czgdp1807** [comment]
@certik This is ready.

**Review by certik — APPROVED** [review]
This looks great! Thank you for this. Go ahead and merge this.

**Pull request merged**
