### PR TITLE
Use block call to allow variables declaration in for loop

### PR DESCRIPTION
**Pull request by Smit-create**
#892

### CODE REVIEW

**Comment by Smit-create** [comment]
The PR is ready for review. I have fixed most of the errors with only one remaining in: `integration_tests/generics_list_01.py`. I am not much familiar with the recent updates on generics.

**Review by czgdp1807 — CHANGES_REQUESTED** [review]
Some changes are needed. I will shepherd this PR later this week.

**Comment by czgdp1807** [comment]
@certik This is ready for review. Let me know if there is anything to be updated here. Otherwise I will clean up the git history.

**Review by certik — APPROVED** [review]
I think this is fine. Why did the ASR tests change?

**Comment by czgdp1807** [comment]
> Why did the ASR tests change?

Its because to store variables declared inside loop body, we need to create a new scope. So, the change is the Symtab ID of some symbol tables increased by some amount (1 or 2 mostly). Nothing to worry about though as Symtab IDs for internal usage of the compiler only and doesn't affect code generation in the backends or the passes.

**Comment by certik** [comment]
I see, that's fine.

**Review by czgdp1807 — APPROVED** [review]

**Pull request merged**
