### PR TITLE
Implement `str` and `bool` runtime functions

### PR DESCRIPTION
**Pull request by namannimmo10**
Inspiration: https://github.com/lcompilers/lpython/issues/1#issuecomment-1002880770

### CODE REVIEW

**Comment by namannimmo10** [comment]
We should do something about this line: https://github.com/lcompilers/lpython/blob/e1b2778dc30d413a6ce3abb698ff52c1598240f9/src/libasr/codegen/asr_to_llvm.cpp#L1518

Nonetheless, the ASR looks good to me.

**Comment by certik** [comment]
Is this an intrinsic function? I don't see it here: https://docs.python.org/3/library/functions.html

Also it's time to refactor this whole function into LFortran's style. Let's not put anymore functions here until we refactor, as it is unmaintainable longterm. Let me know if you know how to do the refactor.

**Comment by namannimmo10** [comment]
> Is this an intrinsic function?

No. We will add a generic function, `str()` down the road, but right now I'm trying to make `str_int` and `str_float` work.

I have two ideas for doing that:
1. Using decorators... 
2. Using type guard:
```python
>>> def str(val: i32 | f64):
...   # "isinstance" type guard
...   if isinstance(val, i32):
...     # type of `val` is narrowed to `i32`
...     return str_int(val)
...   elif isinstance(val, f64):
...     # else, type of `val` is narrowed to `f64`
...     return str_float(val)
...
>>>
```
You are talking about [this file](https://github.com/lcompilers/lpython/blob/main/src/lpython/semantics/comptime_eval.h), right?

**Comment by namannimmo10** [comment]
Once we merge this, I will add the rest.

**Review by certik — APPROVED** [review]
I think that this looks great!

**Pull request merged**
