### PR TITLE
Uniform semantic errors in string slicing .

### PR DESCRIPTION
**Pull request by faze-geek**
Semantic error thrown only for upper index on master , error messages for lower index and step value added.  
```
s="abcdefg"
print(s[1.5:7])
semantic error: slice indices must be integers or None
 --> try.py:4:13
  |
4 |     print(s[1.5:7])
  |             ^^^ 

print(s[1:7:0.5])
semantic error: slice indices must be integers or None
 --> try.py:4:17
  |
4 |     print(s[1:7:0.5])
  |                 ^^^ 

```
Test and reference files ( for invalid upper index ) had been added in #347 , so I'll add them if they are essentially required.

### CODE REVIEW

**Comment by certik** [comment]
Perfect. Can you please add tests for the error messages? Just add the failing test into tests/errors, register them in tests.yaml, and do "./run_tests -u", which will generate reference results and commit them.

**Comment by faze-geek** [comment]
> Perfect. Can you please add tests for the error messages? 

@certik I have done the following . I guess this is good to go in once the tests pass .

**Review by namannimmo10 — APPROVED** [review]
LGTM. Thanks!

**Comment by czgdp1807** [comment]
LGTM as well.

**Review by czgdp1807 — APPROVED** [review]

**Comment by certik** [comment]
Thanks, looks good.

**Pull request merged**
