### PR TITLE
Windows Build Issues fix

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
All the errors has been fixed, while linking or generating the lpython executable (which takes a lot of time maybe 2-5 min) i.e.,
```console
Consolidate compiler generated dependencies of target lpython
[ 99%] Linking CXX executable test_lfortran.exe
[ 100%] Linking CXX executable lpython.exe
```
I get the following warning which goes infinitely:
```
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
../../libasr/libasr.a(evaluator.cpp.obj): In function `LFortran::LLVMModule::get_return_type(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
C:/Users/shock/OneDrive/Desktop/Open_Source/lpython/src/libasr/codegen/evaluator.cpp:92: undefined reference to `llvm::Module::getFunction(llvm::StringRef) const'
C:/Users/shock/OneDrive/Desktop/Open_Source/lpython/src/libasr/codegen/evaluator.cpp:101: undefined reference to `llvm::Type::isIntegerTy(unsigned int) const'
C:/Users/shock/OneDrive/Desktop/Open_Source/lpython/src/libasr/codegen/evaluator.cpp:103: undefined reference to `llvm::Type::isIntegerTy(unsigned int) const'
C:/Users/shock/OneDrive/Desktop/Open_Source/lpython/src/libasr/codegen/evaluator.cpp:108: undefined reference to `llvm::StructType::getName() const'
C:/Users/shock/OneDrive/Desktop/Open_Source/lpython/src/libasr/codegen/evaluator.cpp:110: undefined reference to `llvm::StructType::getName() const'
.
.
[infinite]
.
.
C:/Users/shock/miniconda3/envs/lp/Library/lib/LLVMDemangle.lib(lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.obj):(.xdata[$unwind$?printLeft@?$FloatLiteralImpl@M@itanium_demangle@llvm@@UEBAXAEAVOutputStream@23@@Z]+0xc): undefined reference to `__GSHandlerCheck'    
C:/Users/shock/miniconda3/envs/lp/Library/lib/LLVMDemangle.lib(lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.obj):(.xdata[$unwind$?printLeft@?$FloatLiteralImpl@N@itanium_demangle@llvm@@UEBAXAEAVOutputStream@23@@Z]+0xc): undefined reference to `__GSHandlerCheck'    
C:/Users/shock/miniconda3/envs/lp/Library/lib/LLVMDemangle.lib(lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.obj):(.xdata[$unwind$?printLeft@?$FloatLiteralImpl@O@itanium_demangle@llvm@@UEBAXAEAVOutputStream@23@@Z]+0xc): undefined reference to `__GSHandlerCheck'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src\bin\CMakeFiles\lpython.dir\build.make:151: src/bin/lpython.exe] Error 1
make[1]: *** [CMakeFiles\Makefile2:424: src/bin/CMakeFiles/lpython.dir/all] Error 2
make: *** [Makefile:165: all] Error 2
```

**Comment by Thirumalai-Shaktivel** [comment]
Thus, `./src/bin/lpython` is not generated

**Comment by certik** [comment]
Thanks for this. So it compiles, but does not link?

See if you can figure out how to link it. If you succeed, then we should add it to our CI to test not only with MSVC, but also with mingw. 

If you can't figure it out, we should still add a test, but in that test, we would somehow skip the linking, but build everything else, that way we can test that at least things build, and we will figure out how to fix the linking issue later.

**Comment by Thirumalai-Shaktivel** [comment]
MSVC takes 5 mins 35 sec to build from scratch. It's very high compared to what it takes in Ubuntu!

**Comment by Thirumalai-Shaktivel** [comment]
So, the mingw-w64 seems to work on Ubuntu. It links the llvm and we get the output. I think it's something to do with our CMake for windows mingw-w64?

**Comment by Thirumalai-Shaktivel** [comment]
@certik How is the LLVM linked in MSVC?

**Comment by certik** [comment]
We use the Microsoft Linker and MSVC. It might be that it will not link with MinGW, as we use LLVM built using Conda.

**Comment by Thirumalai-Shaktivel** [comment]
I see, I will look this as well.

**Comment by Thirumalai-Shaktivel** [comment]
It seems we can increase the speed of windows build by using Ninja
@certik What do you think about this?
The build time of MinGW-w64 (halts at the end: lpython.exe) is more than that of MSVC built using Ninja. So, I thought to close this PR.
build takes following on my laptop
Ninja: 3 mins 45 secs
MinGW: 4 min 35 secs
Normal: 7 mins

**Review by certik — APPROVED** [review]
That looks good to me.

**Pull request merged**
