### PR TITLE
Fix parsing for list comprehensions (bison) - New Parser

### LINKED ISSUE #752: [Parser] `Tokenizer Error` on list comprehension example
This example seems to fail on the new parser -

```py
❯ cat examples/expr2.py
[i for (i) in range(5)]
❯ lpyast examples/expr2.py
(Module [(Expr (ListComp (Name i Load) [((Name i Store) (Call (Name range Load) [(ConstantInt 5 ())] []) [] 0)]))] [])
❯ lpyast examples/expr2.py --new-parser
tokenizer error: Parentheses does not match
 --> examples/expr2.py:1:10
  |
1 | [i for (i) in range(5)]
  |          ^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

However, the tokenizer works as expected and doesn't throw any error message when tested independently. Tokenizer's output -

```py
❯ lpy --show-tokens examples/expr2.py
(TOKEN "[") 0:0
(TOKEN "identifier" i) 1:1
(KEYWORD "for") 3:5
(TOKEN "(") 7:7
(TOKEN "identifier" i) 8:8
(TOKEN ")") 9:9
(KEYWORD "in") 11:12
(TOKEN "identifier" range) 14:18
(TOKEN "(") 19:19
(TOKEN "integer" 5) 20:20
(TOKEN ")") 21:21
(TOKEN "]") 22:22
(NEWLINE) 23:23
(EOF) 24:24
```

The part of the code that throws the exception also runs fine when tested individually -

```py
❯ cat examples/expr2.py
(i)
❯ lpyast examples/expr2.py --new-parser
(Module [(Expr (Name i Load))] [])
❯ lpyast examples/expr2.py
(Module [(Expr (Name i Load))] [])
```

### PR DESCRIPTION
**Pull request by krshrimali**
This PR fixes #752, a few details:

1. I realized there was a syntax error raised from the bison parser for the example: `[x for (x) in range(5)]`, and since `[(x) for x in range(5)]` passed - it indicated that this doesn't seem to be a parentheses mismatch error (from the tokenizer).
2. Since `id_item` supported `(<id_list>,)` and not `(<id>)` (notice the commas) - I think that was the issue.
3. Added tests

Sample code: `[(x) for (x) in range(5)]`
AST Tree (for the sample code above):

```bash
└-Module
  |-body=↧
  | └-Expr
  |   └-value=ListComp
  |     |-elt=Name
  |     | |-id=x
  |     | └-expr_contextType=Load
  |     └-generators=↧
  |       └-
  |         |-target=Name
  |         | |-id=x
  |         | └-expr_contextType=Load
  |         |-iter=Call
  |         | |-func=Name
  |         | | |-id=range
  |         | | └-expr_contextType=Load
  |         | |-args=↧
  |         | | └-ConstantInt
  |         | |   |-value=5
  |         | |   └-kind=()
  |         | └-keywords=↧
  |         |-ifs=↧
  |         └-is_async=0
  └-type_ignores=↧
```

P.S: This is my first (attempt) contribution to LPython, so if the tests are in the wrong place or if I'm missing anything, please let me know.

### CODE REVIEW

**Comment by czgdp1807** [comment]
Hey @krshrimali. Nice to see you here. The tests are failing because you need to run the following command from the project root to update reference tests,

```bash
12:52:58:~/lpython_project/lpython % conda activate lp
(lp) 12:53:09:~/lpython_project/lpython % python run_tests.py -u
```

**Comment by krshrimali** [comment]
> Hey @krshrimali. Nice to see you here. The tests are failing because you need to run the following command from the project root to update reference tests,
> 
> ```shell
> 12:52:58:~/lpython_project/lpython % conda activate lp
> (lp) 12:53:09:~/lpython_project/lpython % python run_tests.py -u
> ```
> 
> And merging main into your branch followed by clean build is recommended before executing the above command.

Thanks, @czgdp1807!! I am not sure, since these tests fail for `tests/parser/statements1.py` (diff) but I don't get any changes for this python file after running `python run_tests.py -u`. I did get the list comprehension file, so not too sure about this. Is there anything I'm doing wrong or missing here?

**Comment by czgdp1807** [comment]
> And merging main into your branch followed by clean build is recommended before executing the above command.

Did you try this before executing, `python run_tests.py -u`?

**Review by Thirumalai-Shaktivel — COMMENTED** [review]
Excellent @krshrimali, Thanks for this PR! 
LGTM!

**Comment by krshrimali** [comment]
> 

Thanks, @czgdp1807 - looks like something went wrong when I pushed the files before. Tests pass now, appreciate your comments. I'll wait for other reviews now. :)

**Review by certik — APPROVED** [review]
Looks good. Do you want to squash the last two commits "Add artifacts" into just one "Add artifacts"?

**Comment by czgdp1807** [comment]
May be we can squash merge this PR as its already a very small change.

**Comment by krshrimali** [comment]
@certik - Thanks for reviewing. Do you think we can squash and merge this PR instead? If not, I can squash the last 2 commits. :)

**Comment by krshrimali** [comment]
Update: Squashed the `artifacts` commits into one. Hope this looks good. cc: @certik

**Comment by certik** [comment]
Thanks!

Yes, we can squash the PR, but since @krshrimali was explicitly asking "P.S: This is my first (attempt) contribution to LPython, so if the tests are in the wrong place or if I'm missing anything, please let me know.", and pretty much the only thing missing was just to polish the history, that's why I said it. With a clean history, the PR can just be merged, and we don't need to do any squashing.

**Comment by akshanshbhatt** [comment]
@krshrimali, thanks for working on this!

**Pull request merged**
