### PR TITLE
Ci mamba fix

### PR DESCRIPTION
**Pull request by Vipul-Cariappa**
Builds on top of #2758

### CODE REVIEW

**Comment by Vipul-Cariappa** [comment]
@certik, as I can't write to that branch, I will be using this branch.

**Comment by Vipul-Cariappa** [comment]
I had to skip the `test_bit_length` integration test from `llvm` and `llvm_jit`. I have commented about it on an issue related to `bit_length`. see https://github.com/lcompilers/lpython/issues/1836#issuecomment-2213626743.

**Comment by Vipul-Cariappa** [comment]
@certik, this might be a simpler fix than #2758.
Only had to skip `test_bit_length` integrations test, compared to skipping both `test_llvm` and the integration test.
And we need not pin every single package. I have only pined the necessary packages, and most probably conda will install the newest available versions of the other packages.

**Comment by certik** [comment]
Fixed in https://github.com/lcompilers/lpython/pull/2764.

**Pull request closed without merging**
