### PR TITLE
Remove the Fortran parser completely

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
As per the **Add New Features** section on https://docs.lfortran.org/CONTRIBUTING/
I was looking for the `src/lpython/parser/tokenizer.re` file in the repository, but I could not find the `src/lpython/parser` folder. After searching on the GitHub Repository, I came across this pull request.  

Please, could you possibly share how the current `lpython` is able to generate tokens as well as construct the syntax tree if we do not have tokenizer and parser? If we do have the tokenizer (the file where we have regex to recognize language tokens) and parser (the file where we have grammer rules to construct syntax tree) , could you possibly direct me to these files, please?

**Comment by Thirumalai-Shaktivel** [comment]
Hi @Shaikh-Ubaid,
https://docs.lfortran.org/CONTRIBUTING/ This guide explains how to contribute to the LFortran repository.
LPython is derived from the LFortran repository, so we're currently removing all the Fortran-related things. In this PR, we completely removed the Fortran parser (which was used to parse the Fortran code in LFortran).
Here in LPython, we have not yet started implementing the parser. Actually, we use Python to parse the syntax and generate the AST.
Python AST Node definitions: [Python.asdl](https://github.com/lcompilers/lpython/blob/main/grammar/Python.asdl)
[asdl_py.py](https://github.com/lcompilers/lpython/blob/main/grammar/asdl_py.py) does all the AST generation work.

**Comment by Shaikh-Ubaid** [comment]
> Hi @Shaikh-Ubaid, https://docs.lfortran.org/CONTRIBUTING/ This guide explains how to contribute to the LFortran repository. LPython is derived from the LFortran repository, so we're currently removing all the Fortran-related things. In this PR, we completely removed the Fortran parser (which was used to parse the Fortran code in LFortran). Here in LPython, we have not yet started implementing the parser. Actually, we use Python to parse the syntax and generate the AST. Python AST Node definitions: [Python.asdl](https://github.com/lcompilers/lpython/blob/main/grammar/Python.asdl) [asdl_py.py](https://github.com/lcompilers/lpython/blob/main/grammar/asdl_py.py) does all the parser and AST generation work.

Got it. Thank you!

**Comment by certik** [comment]
Yes, we removed it from LPython, and we will add a Python parser, for example as part of the GSoC project. If you want to see how it would work, you can look here:

https://gitlab.com/lfortran/lfortran/-/tree/master/src/lfortran/parser

**Pull request merged**
