### PR TITLE
C: Support ListRepeat

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lcompilers/lpython/issues/2221

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This PR needs to be rebased after merging/completion of https://github.com/lcompilers/lpython/pull/2224.

**Comment by Shaikh-Ubaid** [comment]
Please note that the support for `ListRepeat` is only added for the `C` backend.

**Review by certik — APPROVED** [review]
I think this is fine.

Is the malloc part in C ever freed?

**Comment by Shaikh-Ubaid** [comment]
>Is the malloc part in C ever freed?

I think it is not freed ever.

```bash
$ git grep "_lfortran_free"
src/libasr/codegen/asr_to_llvm.cpp:    inline void call_lfortran_free(llvm::Function* fn, llvm::Type* llvm_data_type) {
src/libasr/codegen/asr_to_llvm.cpp:        std::string func_name = "_lfortran_free";
src/libasr/codegen/asr_to_llvm.cpp:    inline void call_lfortran_free_string(llvm::Function* fn) {
src/libasr/codegen/asr_to_llvm.cpp:                    call_lfortran_free(free_fn, llvm_data_type);
src/libasr/codegen/llvm_utils.cpp:            std::string func_name = "_lfortran_free";
src/libasr/runtime/lfortran_intrinsics.c:LFORTRAN_API void _lfortran_free(char* ptr) {
src/libasr/runtime/lfortran_intrinsics.h:LFORTRAN_API void _lfortran_free(char* ptr);
```

We should fix it soon. I think it leads to memory leak.

**Comment by certik** [comment]
Yes, it's time to fix all these.

**Pull request merged**
