### PR TITLE
Synchronizing libasr's template instantiation with LFortran

### PR DESCRIPTION
**Pull request by ansharlubis**
Removed functionalities unique to LPython from libasr.

### CODE REVIEW

**Comment by certik** [comment]
@ansharlubis is this ready for review?

**Comment by czgdp1807** [comment]
@ansharlubis Please mark it ready for review whenever you want it to be reviewed. I review non-draft open PRs on a daily basis, so will go through yours as well when you mark it as ready for review.

**Comment by ansharlubis** [comment]
> @ansharlubis Please mark it ready for review whenever you want it to be reviewed. I review non-draft open PRs on a daily basis, so will go through yours as well when you mark it as ready for review.

Got it! I was waiting for the test to pass before requesting a review. (cc @certik )

**Comment by certik** [comment]
@czgdp1807 go ahead and review please.

**Review by czgdp1807 — APPROVED** [review]
My next feature request is to support accepting any rank arrays in a function. I need it to implement reduction function in NumPy such as `np.sum()`, `np.max()`, `np.argmax()`. See an example below,

```python
def sum(array: T[...]) -> T:
    result: T = 0
    for t in itertools.permutations(array.shape):
        result += array[t]
    return result
```

`T[...]` encodes the type of any rank array and the code should be generated according to the function call.

With an `axis` argument things would be slightly different but its doable with a logic similar to above.

**Comment by certik** [comment]
See https://github.com/lfortran/lfortran/issues/1199#issuecomment-1400750193 for any rank. @czgdp1807 can you please merge this PR if it can be merged?

**Comment by czgdp1807** [comment]
> See [lfortran/lfortran#1199 (comment)](https://github.com/lfortran/lfortran/issues/1199#issuecomment-1400750193) for any rank.

Yes, the above comment is for Fortran. For LPython we need a different syntax. One of which is I proposed in https://github.com/lcompilers/lpython/pull/1474#pullrequestreview-1272108760. I guess we should we have a multi-index type. So, we will be able to do `t: MultiIndex[...]` and then use it to index `array: T[...]`.

**Comment by certik** [comment]
I am mainly concerned about the ASR details, I am not worried about syntax right now. So the work is the same for both LPython and LFortran.

**Pull request merged**
