### PR TITLE
Support static functions in C backend

### LINKED ISSUE #1115: C backend - Static Functions
Need to add support to C backend for static functions.

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes #1115 

@certik Does this make sense? Please let me know if any change is required otherwise I will clean up the git history.

### CODE REVIEW

**Comment by certik** [comment]
I think so!

**Comment by czgdp1807** [comment]
Seems clang is not that strict with always inlining recursive functions but GCC is. Working to fix that.

**Comment by czgdp1807** [comment]
Okay I will clean up the git history and merge. I hope that's okay @certik.

**Comment by czgdp1807** [comment]
I have enabled auto-merge. I will update the design in subsequent PRs if needed. It isn't a big change though.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
