### PR TITLE
CPP backend clean ups

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Review by namannimmo10 — APPROVED** [review]

**Comment by certik** [comment]
Isn't it more readable to just write `is_a` instead of `ASR::is_a`? In AST to ASR we have to use the prefix, as we have both AST and ASR, but in libasr, the only `is_a` is in ASR, there is no other representation. You don't want to do this in header files, but in cpp files I think it's fine to shorten it. What do you think?

**Comment by certik** [comment]
I think `is_something` is good if the check is not trivial. If it is as trivial as `is_a<Subroutine_t>` then I think it's not worth it, is it?

**Comment by Smit-create** [comment]
> Isn't it more readable to just write `is_a` instead of `ASR::is_a`?

IMHO, `ASR::is_a` seems to be more apt as I think using namespaces makes it clearer and easier while debugging.

**Review by certik — APPROVED** [review]
I think it's fine to merge.

**Pull request merged**
