### PR TITLE
Convert initialisation at declaration to assignments and fix Variable.value and Variable.m_symbolic_value settings

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lcompilers/lpython/issues/661

### CODE REVIEW

**Review by certik — APPROVED** [review]
I think that this is fine.

The global variables in Python are effectively just like local (and should be handled like local): see #649 for an example. But let's fix it one step at a time. First inside functions, only later let's tackle the code at the global level.

**Comment by czgdp1807** [comment]
The issue is not with global and local variables. Its related to incorrect setting of `value` attribute of `Variable`. The `Variable` node is same for both global and local variables. Therefore it doesn’t matter. There are only two possible situations, either it is fixed completely or it is not fixed at all. In any case, I think its almost done. If I feel that the fix is getting messy then I will split it. Will let you know shortly.

**Comment by czgdp1807** [comment]
@certik This is ready. I am going to keep this PR for the fixes (as they are clean and simple IMO). Please let me know if any change is required. Thanks.

**Comment by czgdp1807** [comment]
Tests pass.

**Comment by certik** [comment]
Looks good, thanks!

**Comment by czgdp1807** [comment]
Great. Fixing #667 right now. Made some comments on your PR, #666

**Pull request merged**
