### PR TITLE
Adds support for str type to ccall

### PR DESCRIPTION
**Pull request by dylon**

### CODE REVIEW

**Comment by dylon** [comment]
File: main.py
```python
from ltypes import ccall

@ccall
def prn(msg: str) -> None:
    pass

prn("Hello World!")
```

File: main.c
```c
#include <stdio.h>

void prn(char * msg) {
  printf("%s\n", msg);
}
```

Compile library:
```shell
clang -shared -o libprn.so main.c
```

Execute:
```shell
PYTHONPATH=~/Workspace/lpython/src/runtime/ltypes LPYTHON_PY_MOD_NAME=prn LPYTHON_PY_MOD_PATH=. python main.py
```

Output:
```
Hello World!
```

**Comment by czgdp1807** [comment]
Looks good. Can we add a test as well?

**Comment by czgdp1807** [comment]
Let's copy chagnes in `test_c_interop_02` from https://github.com/lcompilers/lpython/pull/671/files and apply here.

**Comment by czgdp1807** [comment]
@dylon Would I mind if I do this? LLVM backend works fine. C backend needs some minor changes to get it working. Please let me know if you are okay with me pushing changes to your branch. Thanks.

**Comment by certik** [comment]
I am working on tests right now, almost done.

**Comment by certik** [comment]
This is ready.

**Pull request merged**
