### PR TITLE
[Parser] Add support for unicode identifiers

### PR DESCRIPTION
**Pull request by akshanshbhatt**
Continuation of #948

### CODE REVIEW

**Comment by certik** [comment]
This change looks much better. How much bigger is the generated tokenizer compared to master?

**Comment by certik** [comment]
On my computer:
```console
$ time lpython --show-ast --new-parser a.py --no-color > a.txt
lpython --show-ast --new-parser a.py --no-color > a.txt  0.13s user 0.03s system 96% cpu 0.157 total
```

**Review by certik — APPROVED** [review]
Let's merge this change, since it's a lot simpler.

The only possible downside of this is that it does not reject technically invalid names that start with a Hindi numeral, but if users were requesting this (I don't think they would, or not soon), we could add an optional ASR pass that would check this and report it as an error and users who care about this can run that pass.

**Comment by Thirumalai-Shaktivel** [comment]
Thank you!

**Pull request merged**
