### PR TITLE
Replace BlockCall symbol with the one in current scope

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**
Fixes: #1668

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
The issue was in the `inline_function_calls` pass:
```py
def func() -> i32:
     return 30

def test() -> i32:
    temp: i32 = func()
    return temp

x : i32 
x = test()
print(x)
```
```clojure
(TranslationUnit
    (SymbolTable
        1
        {
            _global_symbols:
                (Module
                    (SymbolTable
                        6
                        {
                            _lpython_main_program:
                                (Function
                                    (SymbolTable
                                        5
                                        {
                                            _lpython_return_variable_func_test:
                                                (Variable
                                                    5
                                                    _lpython_return_variable_func_test
                                                    []
                                                    Local
                                                    ()
                                                    ()
                                                    Default
                                                    (Integer 4 [])
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            _lpython_return_variable_test:
                                                (Variable
                                                    5
                                                    _lpython_return_variable_test
                                                    []
                                                    Local
                                                    ()
                                                    ()
                                                    Default
                                                    (Integer 4 [])
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            temp_test:
                                                (Variable
                                                    5
                                                    temp_test
                                                    []
                                                    Local
                                                    ()
                                                    ()
                                                    Default
                                                    (Integer 4 [])
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            ~empty_block:
                                                (Block
                                                    (SymbolTable
                                                        8
                                                        {
                                                            
                                                        })
                                                    ~empty_block
                                                    []
                                                )
                                        })
                                    _lpython_main_program
                                    (FunctionType
                                        []
                                        ()
                                        Source
                                        Implementation
                                        ()
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        []
                                        []
                                        .false.
                                    )
                                    []
                                    []
                                    [(=
                                        (Var 5 _lpython_return_variable_func_test)
                                        (IntegerConstant 30 (Integer 4 []))
                                        ()
                                    )
                                    (GoTo
                                        1
                                        __1
                                    )
                                    (BlockCall
                                        1
                                        3 ~empty_block
                                    )
                                    (=
                                        (Var 5 temp_test)
                                        (Var 5 _lpython_return_variable_func_test)
                                        ()
                                    )
                                    (=
                                        (Var 5 _lpython_return_variable_test)
                                        (Var 5 temp_test)
                                        ()
                                    )
                                    (GoTo
                                        2
                                        __2
                                    )
                                    (BlockCall
                                        2
                                        5 ~empty_block
                                    )
                                    (=
                                        (Var 6 x)
                                        (Var 5 _lpython_return_variable_test)
                                        ()
                                    )
                                    (Print
                                        ()
                                        [(Var 6 x)]
                                        ()
                                        ()
                                    )]
                                    ()
                                    Public
                                    .false.
                                    .false.
                                ),
                            func:
                                (Function
                                    (SymbolTable
                                        2
                                        {
                                            _lpython_return_variable:
                                                (Variable
                                                    2
                                                    _lpython_return_variable
                                                    []
                                                    ReturnVar
                                                    ()
                                                    ()
                                                    Default
                                                    (Integer 4 [])
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                )
                                        })
                                    func
                                    (FunctionType
                                        []
                                        (Integer 4 [])
                                        Source
                                        Implementation
                                        ()
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        []
                                        []
                                        .false.
                                    )
                                    []
                                    []
                                    [(=
                                        (Var 2 _lpython_return_variable)
                                        (IntegerConstant 30 (Integer 4 []))
                                        ()
                                    )
                                    (Return)]
                                    (Var 2 _lpython_return_variable)
                                    Public
                                    .false.
                                    .false.
                                ),
                            test:
                                (Function
                                    (SymbolTable
                                        3
                                        {
                                            _lpython_return_variable:
                                                (Variable
                                                    3
                                                    _lpython_return_variable
                                                    []
                                                    ReturnVar
                                                    ()
                                                    ()
                                                    Default
                                                    (Integer 4 [])
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            _lpython_return_variable_func:
                                                (Variable
                                                    3
                                                    _lpython_return_variable_func
                                                    []
                                                    Local
                                                    ()
                                                    ()
                                                    Default
                                                    (Integer 4 [])
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            temp:
                                                (Variable
                                                    3
                                                    temp
                                                    []
                                                    Local
                                                    ()
                                                    ()
                                                    Default
                                                    (Integer 4 [])
                                                    Source
                                                    Public
                                                    Required
                                                    .false.
                                                ),
                                            ~empty_block:
                                                (Block
                                                    (SymbolTable
                                                        7
                                                        {
                                                            
                                                        })
                                                    ~empty_block
                                                    []
                                                )
                                        })
                                    test
                                    (FunctionType
                                        []
                                        (Integer 4 [])
                                        Source
                                        Implementation
                                        ()
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        .false.
                                        []
                                        []
                                        .false.
                                    )
                                    []
                                    []
                                    [(=
                                        (Var 3 _lpython_return_variable_func)
                                        (IntegerConstant 30 (Integer 4 []))
                                        ()
                                    )
                                    (GoTo
                                        1
                                        __1
                                    )
                                    (BlockCall
                                        1
                                        3 ~empty_block
                                    )
                                    (=
                                        (Var 3 temp)
                                        (Var 3 _lpython_return_variable_func)
                                        ()
                                    )
                                    (=
                                        (Var 3 _lpython_return_variable)
                                        (Var 3 temp)
                                        ()
                                    )
                                    (Return)]
                                    (Var 3 _lpython_return_variable)
                                    Public
                                    .false.
                                    .false.
                                ),
                            x:
                                (Variable
                                    6
                                    x
                                    []
                                    Local
                                    ()
                                    ()
                                    Default
                                    (Integer 4 [])
                                    Source
                                    Public
                                    Required
                                    .false.
                                )
                        })
                    _global_symbols
                    []
                    .false.
                    .false.
                ),
            main_program:
                (Program
                    (SymbolTable
                        4
                        {
                            _lpython_main_program:
                                (ExternalSymbol
                                    4
                                    _lpython_main_program
                                    6 _lpython_main_program
                                    _global_symbols
                                    []
                                    _lpython_main_program
                                    Public
                                )
                        })
                    main_program
                    [_global_symbols]
                    [(SubroutineCall
                        4 _lpython_main_program
                        ()
                        []
                        ()
                    )]
                )
        })
    []
)
```
Here the statements from the `func` function were copied into the `test()` function (which included the BlockCall and Goto statements used by the previous function inline.)

**Comment by gptsarthak** [comment]
Thank you. Please check if this also fixes https://github.com/lcompilers/lpython/issues/1677

**Comment by certik** [comment]
We need to be careful here, I think you want to duplicate it, don't you?

**Comment by Thirumalai-Shaktivel** [comment]
I thought the `BlockCall` and `Goto` is specific to one function.

If we duplicate it, should I create an ExternalSymbol for the Block?
```
...
(BlockCall
    1
    3 ~empty_block     ! < ---- This is created in another function symtab
)
...
```

**Comment by certik** [comment]
I don't know. I agree that goto is specific to a function. But removing it seems to make the code incorrect. So we need to figure out how to solve this.

**Comment by czgdp1807** [comment]
Correct. We need to duplicate it and then edit `BlockCall` and `Goto` statements in the duplicated body. It should be doable and not that hard AFAICT as of now.

**Comment by Thirumalai-Shaktivel** [comment]
I'm not sure if this new change was a correct fix.

What does the `Block` symbol store?
What is `BlockCall` used for?

**Comment by certik** [comment]
I think the bug is in the inline pass. It must create a unique name for the `~empty_block` block.

**Comment by certik** [comment]
Rather, it looks like the issue is that the Block symbol points to the old location and BlockCall is calling it from the old location, so one gets the following error message:
```
ASR verify pass error: ASR verify: Block ~empty_block should resolve in current scope.
```
caused by:
```
    void visit_BlockCall(const BlockCall_t& x) {
        require(x.m_m != nullptr, "Block call made to inexisting block");
        require(symtab_in_scope(current_symtab, x.m_m),
            "Block " + std::string(ASRUtils::symbol_name(x.m_m)) +
            " should resolve in current scope.");
...
```

So it looks like the nested function pass needs to copy over the Block symbol (duplicate).

**Comment by czgdp1807** [comment]
https://github.com/lcompilers/lpython/pull/1688#issuecomment-1501380458 is the correct approach. If one is not doing it fully then ASR verify pass errors will always be there.

**Comment by Thirumalai-Shaktivel** [comment]
This seems to fix the issue.
@czgdp1807 Please review this carefully; I removed some assignments that were not used. If you feel like reverting something, let me know, and I will make the required changes.

**Comment by czgdp1807** [comment]
> Please review this carefully; I removed some assignments that were not used. If you feel like reverting something, let me know, and I will make the required changes.

If you are not sure then apply changes to LFortran and see if they work there. If they do then we are good. More testing should ensure that we are not facing any bugs.

**Comment by czgdp1807** [comment]
Also, I think we should have a `llvm-fast` option in `integration_tests/CMakeLists.txt`. We should enable it in all the tests possible to make sure that our optimisation passes are also working as expected all the times.

**Comment by certik** [comment]
Yes, we need `--fast` testing in both LFortran and LPython for all llvm tests.

**Comment by Thirumalai-Shaktivel** [comment]
LFortran PR: https://github.com/lfortran/lfortran/pull/1566

**Review by czgdp1807 — APPROVED** [review]

**Pull request merged**
