### PR TITLE
This shows how to parse a tuple

### PR DESCRIPTION
**Pull request by certik**
Related: #719
Closes: #507, #620

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Thank you @certik, the changes is this PR was really helpful. It solved most of the `tuple issues` that I noticed in the `Numpy` repo.

**Comment by Thirumalai-Shaktivel** [comment]
This PR will be ready, once we parse the With_statement, which I will do it tomorrow.

**Comment by Thirumalai-Shaktivel** [comment]
This PR is ready to go in!

**Review by certik — COMMENTED** [review]
Looks great, thanks!

**Pull request merged**
