### PR TITLE
CPP: Fix list repeat issue 2221

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lcompilers/lpython/issues/2221

related https://github.com/lfortran/lfortran/pull/2080

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Although the example shared here https://github.com/lcompilers/lpython/issues/2221 works in this PR, it seems there are more supports needed to make the CPP backend more usable/stable with lists.

**Comment by Shaikh-Ubaid** [comment]
The changes in C, CPP backends in this PR are propagated to LFortran here https://github.com/lfortran/lfortran/pull/2080. It seems to pass the tests there.

**Comment by Shaikh-Ubaid** [comment]
Ready.

**Review by certik — APPROVED** [review]
I think this is fine. Shouldn't you add a new test to test this new functionality?

**Comment by Shaikh-Ubaid** [comment]
>Shouldn't you add a new test to test this new functionality?

I added a reference test. It seems `cpp` as a `--backend` is not yet supported in the `lpython` driver.

**Pull request merged**
