### PR TITLE
Always insert global symbols to`` _global_symbols`` module

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lcompilers/lpython/issues/1727
https://github.com/lcompilers/lpython/issues/1727#issuecomment-1517366001

### CODE REVIEW

**Review by Thirumalai-Shaktivel — APPROVED** [review]
LGTM! Thanks for fixing this
So, from now on, we will always have `two symbols` in the `TranslationUnit`. If the program uses an `IntrinsicFunction` then the `TranslationUnit` also includes that `function` in the `global scope`.

Empty program:
```Clojure
(TranslationUnit
    (SymbolTable
        1
        {
            _global_symbols:
                (Module
                    (SymbolTable
                        3
                        {
                            
                        })
                    _global_symbols
                    []
                    .false.
                    .false.
                ),
            main_program:
                (Program
                    (SymbolTable
                        2
                        {
                            
                        })
                    main_program
                    []
                    []
                )
        })
    []
)
```

**Comment by czgdp1807** [comment]
Thanks for pointing out. I don't create `_global_symbols` now if it global scope doesn't have any user defined symbols. Now the behaviour will be same as `main` branch when the input file is empty.

**Review by certik — APPROVED** [review]
I think it looks good, thanks for fixing it!

**Comment by certik** [comment]
Hm, this PR broke `--disable-main`, it now always inserts `main`:
```console
(lp) lpython/integration_tests(main) $ lpython --show-c --disable-main import_order_01.py -I.
#include <inttypes.h>

#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <lfortran_intrinsics.h>

#define ASSERT(cond)                                                           \
    {                                                                          \
        if (!(cond)) {                                                         \
            printf("%s%s", "ASSERT failed: ", __FILE__);                       \
            printf("%s%s", "\nfunction ", __func__);                           \
            printf("%s%d%s", "(), line number ", __LINE__, " at \n");          \
            printf("%s%s", #cond, "\n");                                       \
            exit(1);                                                           \
        }                                                                      \
    }
#define ASSERT_MSG(cond, msg)                                                  \
    {                                                                          \
        if (!(cond)) {                                                         \
            printf("%s%s", "ASSERT failed: ", __FILE__);                       \
            printf("%s%s", "\nfunction ", __func__);                           \
            printf("%s%d%s", "(), line number ", __LINE__, " at \n");          \
            printf("%s%s", #cond, "\n");                                       \
            printf("%s", "ERROR MESSAGE:\n");                                  \
            printf("%s%s", msg, "\n");                                         \
            exit(1);                                                           \
        }                                                                      \
    }


struct dimension_descriptor
{
    int32_t lower_bound, length;
};

// Implementations
int32_t f()
{
    int32_t _lpython_return_variable;
    _lpython_return_variable = 42;
    return _lpython_return_variable;
}

void main1()
{
    int32_t a;
    a = f();
    printf("%d\n", a);
}

int main(int argc, char* argv[])
{
    return 0;
}
```
Hopefully it can be fixed with a subsequent PR, otherwise we'll need to revert it.

**Comment by czgdp1807** [comment]
Let me see. Probably a corner case.

**Pull request merged**
