### PR TITLE
WASM_X64: Support initial testing infrastructure

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` adds initial support for testing the `wasm_x64` backend. It also enables testing this backend at `CI`.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
The bottom-most `three` commits are part of #1364. The remaining commits are part of this `PR`. I will rebase this `PR` after merging of #1364.

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Review by certik — APPROVED** [review]
Thanks, looks good!

**Comment by Shaikh-Ubaid** [comment]
Rebased this. Adding it to auto-merge as it seems approved.

**Pull request merged**
