### PR TITLE
Improve comparison of dissimilar types

### LINKED ISSUE #2593: Comparison on dissimilar types can be improved
Comparing dissimilar types throws a semantic error stating type mismatch.

### Checking equality
```python
integer: i32 = 1
integer_list: list[i32] = [1, 2, 3, 4, 5]
print(integer == integer_list)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
semantic error: Type mismatch in comparison operator, the types must be compatible
 --> ./examples/example.py:5:7
  |
5 | print(integer == integer_list)
  |       ^^^^^^^    ^^^^^^^^^^^^ type mismatch ('i32' and 'list[i32]')


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
```

### Checking inequality
```python
integer: i32 = 1
integer_list: list[i32] = [1, 2, 3, 4, 5]
print(integer != integer_list)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
semantic error: Type mismatch in comparison operator, the types must be compatible
 --> ./examples/example.py:5:7
  |
5 | print(integer != integer_list)
  |       ^^^^^^^    ^^^^^^^^^^^^ type mismatch ('i32' and 'list[i32]')


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
```
Similar error is thrown for other operators.

### PR DESCRIPTION
**Pull request by kmr-srbh**
Fixes #2593 

Comparison on dissimilar types can be handled the way CPython does - return `True` when comparing for inequality and `False` when comparing for equality. Throw a semantic error when using `>`, `>=`, `<` and `<=`.

### Checking equality
```python
integer: i32 = 1
integer_list: list[i32] = [1, 2, 3, 4, 5]
print(integer == integer_list)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
semantic error: Type mismatch in comparison operator, the types must be compatible
 --> ./examples/example.py:5:7
  |
5 | print(integer == integer_list)
  |       ^^^^^^^    ^^^^^^^^^^^^ type mismatch ('i32' and 'list[i32]')


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
```
Similar error is thrown for other operators.

### Checking equality
```python
integer: i32 = 1
integer_list: list[i32] = [1, 2, 3, 4, 5]
print(integer == integer_list)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
False
```
### Checking inequality
```python
integer: i32 = 1
integer_list: list[i32] = [1, 2, 3, 4, 5]
print(integer != integer_list)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
True
```
### Checking greater than or equal to (>=) [similar for other operators]
```python
integer: i32 = 1
integer_list: list[i32] = [1, 2, 3, 4, 5]
print(integer >= integer_list)
```
```console
semantic error: Comparison operator not supported between instances of 'i32' and 'list[i32]'
 --> ./examples/example.py:5:7
  |
5 | print(integer >= integer_list)
  |       ^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
```

### CODE REVIEW

**Comment by kmr-srbh** [comment]
The failing tests are those which checked for the semantic error before.

**Comment by kmr-srbh** [comment]
In CPython doing something like `1 == 1.0` returns `True` as the value is the same. Should we do something similar, or is it okay to throw an error?

**Comment by Shaikh-Ubaid** [comment]
>@certik In CPython 1 == 1.0 returns True as the value is the same. Should we do something similar, or is it okay to throw an error?

We currently throw an error because LPython has strict type checking and does not do implicit casting. The design of LPython is such that everything has to be explicitly casted by the user.

**Comment by Shaikh-Ubaid** [comment]
I feel this PR is not needed. I am temporarily marking this as draft.

**Comment by Shaikh-Ubaid** [comment]
Let's close this PR for now. We can reopen later if needed.

**Pull request closed without merging**
