### PR TITLE
Rename `LFORTRAN_ASSERT` to `LCOMPILERS_ASSERT `

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Let's merge this after the next libasr sync.

**Comment by czgdp1807** [comment]
Same here. Please make one such PR in LFortran. We will merge both together.

**Comment by czgdp1807** [comment]
This seems redundant in the presence of https://github.com/lcompilers/lpython/pull/1341. Is that the case?

**Comment by Thirumalai-Shaktivel** [comment]
Yup, I thought to split each commits into a separate PR. So, that PR depends on this.

**Comment by Thirumalai-Shaktivel** [comment]
Okay, let me use this PR for some other changes.

**Comment by czgdp1807** [comment]
Let's combine all the renames in a single PR and get it in. I am closing this PR.

**Comment by Thirumalai-Shaktivel** [comment]
But, @certik said to split the things so that it would be easy to review.

**Comment by czgdp1807** [comment]
I guess these are just renames. Ctrl + F and Replace All. Is there any logical change present here that needs thorough review?

**Pull request closed without merging**
