### PR TITLE
Refactor: Several Improvements

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Review by czgdp1807 — COMMENTED** [review]
For a compiler like ours which is in fast pace development mode, I wouldn’t remove code which never gets triggered by the tests. Instead I would prefer adding tests which trigger that code. Its a time consuming process but that’s better than removing unused code because they might be having some important logic we might have written but missed to add tests for it (< 100% code coverage is very normal).

**Comment by Shaikh-Ubaid** [comment]
>For a compiler like ours which is in fast pace development mode, I wouldn’t remove code which never gets triggered by the tests.

Actually, it is not about the tests. The `current_module` value is always `nulltpr` (it is assigned this value during its initialization and its value is never updated. The code itself is dead code.

**Comment by Shaikh-Ubaid** [comment]
Ready.

**Comment by certik** [comment]
Can you send a PR to LFortran for this change in libasr as well? Let's see if it breaks anything there.

**Comment by Shaikh-Ubaid** [comment]
>Can you send a PR to LFortran for this change in libasr as well? Let's see if it breaks anything there.

Sure, please see https://github.com/lfortran/lfortran/pull/1989.

**Review by certik — APPROVED** [review]
I think that this is fine, it works in LFortran.

**Pull request merged**
