### PR TITLE
Pass CompilerOptions as argument to python_ast_to_asr()

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
closes https://github.com/lcompilers/lpython/issues/1272

### CODE REVIEW

**Review by czgdp1807 — APPROVED** [review]
@certik's approval will be required for final merge.

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval, @czgdp1807.

**Review by certik — APPROVED** [review]
I think that this is good, thanks!

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval and merging!

**Pull request merged**
