### PR TITLE
C: Use unique names for variables

### PR DESCRIPTION
**Pull request by Smit-create**
#2129

### CODE REVIEW

**Comment by Smit-create** [comment]
@certik please let me know if this is the correct approach to move further. There are many tests that still fail and it would require fixes to complete this.

**Comment by certik** [comment]
I think so. This seems what I was thinking.

**Comment by certik** [comment]
To help with the tests, let's hide it behind a compiler option, that way the new name would only be used with the option is given, so current tests should pass.

**Comment by certik** [comment]
Sure. Depends what the failures are --- the issue with unique names is that all the C tests then will fail, as the name is changing with every run (as it should!).

**Comment by Smit-create** [comment]
I have added the fix, but it's kind of hack-ish as we need to keep in mind about unique_id  while emitting the symbol name which can fail easily. How about writing a pass if we have `--generate-object-code`, then it would replace all the symbol_names with unique names. This would also help with any such backend where there would be linking issues like C, C++, etc.

**Comment by certik** [comment]
I think writing the ASR pass will be better, as it will fix this issue for all the backends. Here is what the pass could do:

* all module level symbols will receive proper name mangling: prepend module name, and optional unique hash (depending on a compiler option).

I think this might be as easy as just modifying the symbol table, since we don't reference things by name, except in ExternalSymbols, so those would have to be updated too.

**Comment by Smit-create** [comment]
I'll keep this PR open as all the tests pass successfully. I'll work on writing a pass in a new PR tomorrow morning.

**Comment by Smit-create** [comment]
Completed in #2149

**Pull request closed without merging**
