### PR TITLE
Added test based on basic_new_heap function

### PR DESCRIPTION
**Pull request by anutosh491**

### CODE REVIEW

**Comment by anutosh491** [comment]
TODO for subsequent PRs:
* [x] Add a line under print to also test using assert: `assert basic_str(x) == "pi"`
* [ ] enable LLVM backend (we need to add `llvm_sym` into CMake and add this label)
* [ ] add a test for `basic_new_stack` (this should be a new test file)

**Comment by anutosh491** [comment]
I've added the `assert` check in this pr itself as it was simple 1 line addition . I'll address the remaining TODO's through subsequent prs.

**Comment by anutosh491** [comment]
I've added the `assert` check in this pr itself as it was simple 1 line addition . I'll address the remaining TODO's through subsequent prs.

**Comment by anutosh491** [comment]
cc @certik All tests seems to pass . I think this could be merged .

**Review by certik — APPROVED** [review]
Yes, this is good. Thanks!

**Comment by anutosh491** [comment]
Thanks . I'll create the new pull requests now!

**Pull request merged**
