### PR TITLE
Fix bug in printing a list

### LINKED ISSUE #2639: Severe Bug: Calling a function inside `print()` leads to infinite function calls
The issue occurs with functions which **modify** other objects and return a value.

### Failing code

```python
from lpython import i32

my_list: list[i32] = []

def add_item(item: i32) -> list[i32]:
    my_list.append(item)
    return my_list

print(add_item(1))
```

### CPython
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ python3 ./examples/example.py
[1]
```

### LPython
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ^C
```

The workaround is to store the return value in a variable and then print it.

```python
from lpython import i32

my_list: list[i32] = []

def add_item(item: i32) -> list[i32]:
    my_list.append(item)
    return my_list

my_new_list: list[i32] = add_item(1)
print(my_new_list)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
[1]
```

### PR DESCRIPTION
**Pull request by advikkabra**
Fixes #2639 .
I am not sure how/where to test this, but this fixes the issue by making an auxiliary variable in the ASR.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
We should add an integration test. We can have an assert on the length of the list, couple initial elements and couple ending elements.

**Comment by Shaikh-Ubaid** [comment]
>but this fixes the issue by making an auxiliary variable in the ASR.

Could you describe what the issue was and how creating an auxiliary variable fixes it?

**Comment by advikkabra** [comment]
> > but this fixes the issue by making an auxiliary variable in the ASR.
> 
> Could you describe what the issue was and how creating an auxiliary variable fixes it?

While calling a function which modifies the list in a print function, it repeatedly called the function. This was because in the loop made to print the list, the function was called everytime the length of the list was accessed, so it kept adding elements. By making an auxiliary variable, it keeps the length constant.

**Comment by Shaikh-Ubaid** [comment]
I checked the test case locally. It seems to fail for me.
```console
https://anydesk.com/en

**Comment by Shaikh-Ubaid** [comment]
I checked the solution locally. It seems to fail for me.
```console
% cat examples/expr2.py 
from lpython import i32

def test_issue_2639():
    l: list[i32] = [1, 2]

    def add_item(i: i32) -> list[i32]:
        l.append(i)
        return l

    print(add_item(3))
    print(l)
    assert len(l) == 3
    assert l[0] == 1
    assert l[1] == 2
    assert l[2] == 3


test_issue_2639()
% lpython examples/expr2.py
[1, 2, 3]
[1, 2, 3, 3, 3, 3]
AssertionError
```

**Comment by Shaikh-Ubaid** [comment]
The tests fail for the `C` backend (at the CI and on my system locally).
```console
% ./integration_tests/run_tests.py -b c
...
99% tests passed, 1 tests failed out of 290

Label Time Summary:
c           =   2.46 sec*proc (290 tests)
cpython     =   1.78 sec*proc (275 tests)
llvm        =   2.39 sec*proc (288 tests)
wasm        =   0.83 sec*proc (38 tests)
wasm_x64    =   0.08 sec*proc (23 tests)
wasm_x86    =   0.04 sec*proc (12 tests)
x86         =   0.00 sec*proc (1 test)

Total Test time (real) =   0.77 sec

The following tests FAILED:
        109 - test_list_11 (Failed)
Errors while running CTest
Command failed: ctest -j8 --output-on-failure
```
@advikkabra Can you look into it?

**Comment by advikkabra** [comment]
I think the issue is with nested functions. When the function is not nested it works. I think nested functions might need to be reworked.

**Review by Shaikh-Ubaid — APPROVED** [review]

**Pull request merged**
