### PR TITLE
WASM_X86: Support float types

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This PR adds initial support for float data type in `wasm_x86` backend.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This currently segfaults
```bash
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ cat examples/expr2.py 
def main0():
    x: f64
    x = 2.1

main0()
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ lpython examples/expr2.py --backend wasm_x86 -o tmp
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ ./tmp 
Segmentation fault (core dumped)
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ 
```

**Comment by certik** [comment]
I think for floating point you want to use the xmm0 registers. Don't use this old floating point stack, it's not used anymore for passing arguments to/from functions and I don't recommend using it at all.

If it can't be used from 32 bit then let's forget about floating point.

Try this:
```c
int main() {
    float x;
    x = 3.4;
    x = x + 1;
    return 0;
}
```
and
```console
$ gcc -S -c a.c -o a.s && cat a.s
	.file	"a.c"
	.text
	.globl	main
	.type	main, @function
main:
.LFB0:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register 6
	movss	.LC0(%rip), %xmm0
	movss	%xmm0, -4(%rbp)
	movss	-4(%rbp), %xmm1
	movss	.LC1(%rip), %xmm0
	addss	%xmm1, %xmm0
	movss	%xmm0, -4(%rbp)
	movl	$0, %eax
	popq	%rbp
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE0:
	.size	main, .-main
	.section	.rodata
	.align 4
.LC0:
	.long	1079613850
	.align 4
.LC1:
	.long	1065353216
	.ident	"GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0"
	.section	.note.GNU-stack,"",@progbits
```
This should give you an idea how the floating point works.


I see, in 32bits it uses the old stack:
```console
$ gcc -m32 -S -c a.c -o a.s && cat a.s
	.file	"a.c"
	.text
	.globl	main
	.type	main, @function
main:
.LFB0:
	.cfi_startproc
	pushl	%ebp
	.cfi_def_cfa_offset 8
	.cfi_offset 5, -8
	movl	%esp, %ebp
	.cfi_def_cfa_register 5
	subl	$16, %esp
	call	__x86.get_pc_thunk.ax
	addl	$_GLOBAL_OFFSET_TABLE_, %eax
	flds	.LC0@GOTOFF(%eax)
	fstps	-4(%ebp)
	flds	-4(%ebp)
	fld1
	faddp	%st, %st(1)
	fstps	-4(%ebp)
	movl	$0, %eax
	leave
	.cfi_restore 5
	.cfi_def_cfa 4, 4
	ret
	.cfi_endproc
.LFE0:
	.size	main, .-main
	.section	.rodata
	.align 4
.LC0:
	.long	1079613850
	.section	.text.__x86.get_pc_thunk.ax,"axG",@progbits,__x86.get_pc_thunk.ax,comdat
	.globl	__x86.get_pc_thunk.ax
	.hidden	__x86.get_pc_thunk.ax
	.type	__x86.get_pc_thunk.ax, @function
__x86.get_pc_thunk.ax:
.LFB1:
	.cfi_startproc
	movl	(%esp), %eax
	ret
	.cfi_endproc
.LFE1:
	.ident	"GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0"
	.section	.note.GNU-stack,"",@progbits
```

Let's not worry about it then. I think we have exhausted stuff that can be reused.

I would recommend going to 64bit and getting that working well for everything.

Do you know how to do a 64bit backend, or do you want to start it together?

**Comment by Shaikh-Ubaid** [comment]
>Don't use this old floating point stack, it's not used anymore for passing arguments to/from functions and I don't recommend using it at all.

Got it.

>I would recommend going to 64bit and getting that working well for everything.

Got it.

>Do you know how to do a 64bit backend, or do you want to start it together?

Sir, I think it would be really helpful if we start it together.

**Comment by Shaikh-Ubaid** [comment]
**Example:**
```bash
(lp) lpython$ cat examples/expr2.py 
def main0():
    print(5)
    print(27.14)
    print(-23)
    print("hello")
    print(548.48)
    print("you")
    print(55)
    print(-55)
    x: f64 = 123.45
    y: f64 = x
    print(x)
    print("hi")
    print(y)
    print("end")
main0()
(lp) lpython$ lpython examples/expr2.py --backend wasm_x86 -o tmp > main.asm
(lp) lpython$ ./tmp
5
27.13999939
-23
hello
548.47998047
you
55
-55
123.44999695
hi
123.44999695
end

(wasm_asm) lpython$ nasm -fbin main.asm && chmod +x main && ./main
5
27.13999939
-23
hello
548.47998047
you
55
-55
123.44999695
hi
123.44999695
end
(wasm_asm) lpython$ 
```

To print a floating-point number, we are currently printing its `integer` part, followed by a `'.'` (dot) and then the fractional part of the number (multiplying by `100000000` and then printing it as an `integer`).

**Comment by Shaikh-Ubaid** [comment]
I completed this PR for experience and learning. I think the experience will be helpful for us while supporting `floating-point` in `wasm_x64` backend.

**Comment by Shaikh-Ubaid** [comment]
This is ready.

**Review by certik — APPROVED** [review]
I think these changes are fine, thanks for finishing it up. It's a good step towards using the vector registers.

**Pull request merged**
