### PR TITLE
Add built-in `sum()` 

### PR DESCRIPTION
**Pull request by faze-geek**
`sum()` is a useful inbuilt function in python. Compared to `fsum()` from `math` class it is more commonly used for smaller inputs. It Is also faster as it can be used directly used and does not convert the summation value into `float `on each iteration unlike `floating-point sum`.

```
import math
def main0():
    print(sum([1,2,3,4,5]))
    print(math.fsum([1,2,3,4,5]))

main0()

(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ python try.py
15
15.0
(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ ./src/bin/lpython try.py
15
1.50000000000000000e+01
```
For now only the `list` iterable is compatible with this function

### CODE REVIEW

**Comment by faze-geek** [comment]
@Thirumalai-Shaktivel Made this pr from my ` wsl` since windows set up was still giving some trouble in updating references. Could you have a look at it? I wonder why the tests are not running ?

**Comment by Shaikh-Ubaid** [comment]
>I wonder why the tests are not running ?

I had experienced this previously. Probably some issue at GitHub's end. I think just pushing again would run the CI tests.

**Comment by faze-geek** [comment]
> I think just pushing again (maybe after rebasing) would run the CI tests.

Sure,
`git rebase main` gives `Current branch sum is up to date.` Should I make a minor tweak and push again ?

**Comment by Shaikh-Ubaid** [comment]
>Should I make a minor tweak and push again ?

Yes, try it.

>Or if you are aware of how to fetch a branch, I would like to restore it in my windows and then push from there. Thanks!

I follow these steps to pull branches.
1. add the particular remote: `git remote add faze-geek git@github.com:faze-geek/lpython.git`
2. fetch remote info: `get fetch faze-geek`
3. checkout the desire branch: `git checkout sum` (Unsure what happens if you already have a branch with that same name)
4. now you can work on it just like a normal branch.

**Comment by faze-geek** [comment]
I pushed a minor tweak ,still no luck. I'll try closing and reopening to make the tests again.

**Comment by Shaikh-Ubaid** [comment]
Please also resolve the conflicts and then let's see if the CI runs.

**Comment by Shaikh-Ubaid** [comment]
The CI tests now run.

@faze-geek I think your local main branch is not updated. The commits just before your commits were around `20` days old. As you shared `git rebase main` gives `Current branch sum is up to date`, maybe, you should first update your local `main` branch by:

```bash
git checkout main
git pull --rebase

// now checkout your branch and rebase over main
git checkout sum
git rebase main
```
I just did the above and the tests ran.

**Comment by Thirumalai-Shaktivel** [comment]
Yup. If there are conflicts with the main branch, the actions don't run by default.

**Review by czgdp1807 — APPROVED** [review]
LGTM.

**Review by certik — APPROVED** [review]

**Comment by faze-geek** [comment]
Thanks @Shaikh-Ubaid for the help and others for going through the pr.

The motivation for this pr was that I'm interested in the `Implement Modules from Python standard library` project for GSOC'23. I am having conversations with @Madhav2310 through mail for ideas. I intend on going through his work and refactoring/improving it wherever possible in the near future. Thanks again !

**Pull request merged**
