### PR TITLE
Modulo(3rd argument) added to pow

### PR DESCRIPTION
**Pull request by Madhav2310**

### CODE REVIEW

**Comment by czgdp1807** [comment]
I think you haven't updated reference tests. Please run, `python run_tests.py -u`.

**Comment by czgdp1807** [comment]
@Smit-create I just met @Madhav2310. He said that he is facing some issues with overload operator (he received an error saying only 2 arguments are accepted by 3 provided). Can you fetch his branch and try to run the tests on your machine locally? Let me know if you face the same issue.

**Comment by Smit-create** [comment]
Yes, I get the same error as:
```
semantic error: Arguments do not match for any generic procedure, pow
  --> expr.py:22:16
   |
22 |     assert abs(pow(i,j,k) - 4) < eps
   |                ^^^^^^^^^^ 
```

Overload is working fine for the following example:
```py
@overload
def a(x: i32) -> i32:
    return x+1

@overload
def a(x: i32, y:i32) -> i32:
    return x+y

def f():
    print(a(2), a(5, 6))

f()
```

**Comment by czgdp1807** [comment]
Can you try for three examples?

**Comment by Smit-create** [comment]
> Can you try for three argument example?

Works fine. Even this diff also works:
```diff
diff --git a/src/runtime/math.py b/src/runtime/math.py
index ee0bbed29..81a991713 100644
--- a/src/runtime/math.py
+++ b/src/runtime/math.py
@@ -615,3 +615,9 @@ def remainder(x: f64, y: f64) -> f64:
     if x - y*q > y*(q + 1) - x:
         return x - y*(q + 1)
     return x - y*q
+
+def f():
+    r: i32
+    r = pow(102, 3, 121)
+    print(r)
+f()
```
It prints `38`

**Comment by czgdp1807** [comment]
Well, then last option to reproduce @Madhav2310 's error is to just fetch his branch and run the tests locally with his code changes. @namannimmo10 and @Smit-create Can you please do that?

**Comment by Smit-create** [comment]
Ahhh, I got that error because I didn't import `pow` from `math.py`. The error which Madhav is getting is due to CPython:
```
TypeError: pow expected 2 arguments, got 3
```

**Comment by Smit-create** [comment]
CPython's math doesn't have 3 args.
```py
Python 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:30:18) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import pow
>>> pow(23, 24, 13)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pow expected 2 arguments, got 3
```

**Comment by czgdp1807** [comment]
I see. The builtin `pow` has three arguments not the `math.pow`. @Madhav2310 used 3 arguments with `math.pow`. I think he should add a separate test for [builtin pow](https://docs.python.org/3/library/functions.html#pow). Anyways, @Smit-create did this so it should be fixed now.

**Review by czgdp1807 — APPROVED** [review]
Looks good to me.

**Review by namannimmo10 — COMMENTED** [review]
LGTM.

**Pull request merged**
