### PR TITLE
Creating dict iterators outside the user loops

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/lcompilers/lpython/issues/983#issuecomment-1218136744

Benchmarks with this branch - https://gist.github.com/czgdp1807/e7f7b6ca52c57b16b27ec8d0259c6d4a

### CODE REVIEW

**Review by certik — APPROVED** [review]
Looks good. Are the `dict_api->set_iterators();` a no-op if no dictionaries are used? Or is the some performance overhead for each while loop, whether or not it uses a dictionary?

**Comment by czgdp1807** [comment]
> Are the `dict_api->set_iterators();` a no-op if no dictionaries are used?

Yes. I am yet to optimize it slightly like setting `dict_api->is_dict_present=false` at the entry point of `visit_Program`, `visit_Function` so that we don't create iterators if no dict is used in a given scope.

**Comment by czgdp1807** [comment]
@certik This is ready. Is there anything to be changed here?

**Review by certik — APPROVED** [review]
No, go ahead and merge.

**Pull request merged**
