### PR TITLE
Supporting initialisation with empty list in ASR

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lcompilers/lpython/issues/859

### CODE REVIEW

**Comment by czgdp1807** [comment]
Well its segfaulting on Ubuntu. Will try to reproduce this on my linux machine tomorrow.

**Comment by czgdp1807** [comment]
I think this is happening because initial capacity of the `list` is `0` and hence doubling always produces `0`. On my mac this works fine (probably mac safe gaurds `malloc` implementation against this corner case of `0` input but linux doesn't). I will confirm tomorrow.

**Comment by certik** [comment]
That's a fine solution I think. The PR looks ok.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
