### PR TITLE
Add cmath polar functions

### PR DESCRIPTION
**Pull request by virendrakabra14**
Adds `phase`, `polar`, and `rect` functions to `cmath` module.

### CODE REVIEW

**Comment by virendrakabra14** [comment]
I tried using (LPython) `math` functions in `cmath`, but the import failed with this message
```
Module __main__ dependencies must contain math because a function present in it is getting called in __main__
```

I wasn't sure on where to add this dependency, so I created `rect` function in `lfortran_intrinsics` files.

**Comment by virendrakabra14** [comment]
The error was due to an inconsistent return type.

Running these commands locally did not give any error:
```
python run_tests.py -u
./run_tests.py
cd ./integration_tests
./run_tests.py
```

However the tests here (GitHub workflow) pointed that.
Can these tests be run locally as well?

**Comment by czgdp1807** [comment]
> I tried using (LPython) `math` functions in `cmath`, but the import failed with this message
> 
> ```
> Module __main__ dependencies must contain math because a function present in it is getting called in __main__
> ```
> 
> I wasn't sure on where to add this dependency, so I created `rect` function in `lfortran_intrinsics` files.

Can you share the exact LPython command you followed?

**Comment by czgdp1807** [comment]
@virendrakabra14 I pushed some changes, let's see if they work with Windows CI or not.

**Comment by virendrakabra14** [comment]
> > I tried using (LPython) `math` functions in `cmath`, but the import failed with this message
> > ```
> > Module __main__ dependencies must contain math because a function present in it is getting called in __main__
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I wasn't sure on where to add this dependency, so I created `rect` function in `lfortran_intrinsics` files.
> 
> Can you share the exact LPython command you executed?

I was using `import math` in `cmath.py` and using sin, cos functions. Test file `test_cmath.py` was same as the current one. Then
```
lpython ./integration_tests/test_cmath.py
```
gave that error - which I think is due to importing `math` in `cmath`.

**Comment by czgdp1807** [comment]
Also, eventually we might implement all these intrinsics using `IntrinsicFunction` infrastructure and provide direct ASR implementations for their functions. So if calling into C can be avoided then it should be. Functions like, `_lfortran_dsin`, `_lfortran_dcos` can also be done via ASR directly (by using some approximation algorithms to produce outputs for `sin` and `cos` calls).

**Review by czgdp1807 — APPROVED** [review]

**Review by certik — APPROVED** [review]

**Pull request merged**
