### PR TITLE
Rename `LFortranException` to `LCompilersException`

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by namannimmo10** [comment]
Can you also raise a corresponding MR in LFortran?

**Review by certik — APPROVED** [review]
I think that this is fine. Can you please do the same change in LFortran as well? Let's merge both PRs together.

**Comment by Smit-create** [comment]
LFortran MR: https://gitlab.com/lfortran/lfortran/-/merge_requests/1836

**Comment by certik** [comment]
Sorry this got out of sync. Can you please rebase both PRs against LPython/LFortran and try again?

**Review by namannimmo10 — APPROVED** [review]

**Pull request merged**
