### PR TITLE
Free up memory at the end of scope

### PR DESCRIPTION
**Pull request by advikkabra**
Free lists, dictionaries and sets when they go out of scope. This is not complete, as there are still some places where memory is being leaked.

### CODE REVIEW

**Comment by certik** [comment]
This is freeing some memory used by the compiler, correct?

There is a separate issue of freeing the memory at runtime, and that should be fixed by explicit ASR support for finalization: https://github.com/lfortran/lfortran/issues/3770#issuecomment-2145669584.

**Comment by advikkabra** [comment]
Yes, this is memory freeing at runtime. I did not know about the explicit ASR support, so this PR can be finished when that ASR support is ready.

**Comment by certik** [comment]
It would be good though to work on that, if you want to give it a shot, that would be awesome.

**Comment by advikkabra** [comment]
I'll try my hand at it.

**Pull request closed without merging**
