### PR TITLE
WASM, WAT: Add wasm and wat backends

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` adds support for the `wasm` and `wat` backends.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Review by certik — APPROVED** [review]
Is the libasr simply copied from LFortran? If so, then this is fine.

**Comment by Shaikh-Ubaid** [comment]
>Is the libasr simply copied from LFortran? If so, then this is fine.

Only the `wasm` related source code files have been copied and pasted in the commit https://github.com/lcompilers/lpython/pull/1046/commits/81a532df6c6c0fa02cc19c8e57854350ae809025. Also, it seems in `lpython` all the statements in global scope are contained in a function  named `_lpython_main_program` in the global scope. `wasm` backend did not yet have support for declaring and defining functions in global scope. Therefore an extra commit [WASM: Support functions in global_scope](https://github.com/lcompilers/lpython/pull/1046/commits/2243028691e2f373610fe190e0960e33b028b666) was added to support functions in global scope.

Please, could you possibly share if it is fine?

**Comment by Shaikh-Ubaid** [comment]
I resolved the conflicts.

**Review by certik — APPROVED** [review]
I think this is fine.

Make sure you keep the WASM part synchronized with LFortran by submitting a PR to LFortran with any improvements that you had to do for LPython.

**Comment by Shaikh-Ubaid** [comment]
>Make sure you keep the WASM part synchronized with LFortran by submitting a PR to LFortran with any improvements that you had to do for LPython.

Yes, got it.

**Pull request merged**
