### PR TITLE
CI: Provide release flags, exclude -march=native

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
>I think we just need to lower the optimization options, perhaps keep -O3, but remove -march=native or something like that.

towards https://github.com/lcompilers/lpython/issues/2162#issuecomment-1644965229

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
I am unsure if the changes in this PR are the perfect fix. This seems to be more of an experimental PR. I think we can later try other steps/approaches if the failure in Release build is still experienced post merging of this PR.

**Review by czgdp1807 — COMMENTED** [review]
So `-O3` optimisations weren't applied in the release build before this PR?

**Comment by Shaikh-Ubaid** [comment]
>So -O3 optimisations weren't applied in the release build before this PR?

I think they were being applied. 

https://github.com/lcompilers/lpython/blob/634177d3ff5be102a71d64fe2d80670c85f93661/cmake/UserOverride.cmake#L12

In this PR, I just excluded the `-march=native` flag.

**Comment by certik** [comment]
Yes, let's try this and see.

**Pull request merged**
