### PR TITLE
Using all proccessors for building (in build1.sh script)

### PR DESCRIPTION
**Pull request by ronnuriel**
Signed-off-by: Ron Nuriel <rnuriel@gsitechnology.com>

### CODE REVIEW

**Review by czgdp1807 — APPROVED** [review]
I am +1 on this change.

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
This change is fine with me, but note that this does *not* mean "all processors", but rather it means maximum threads allowed by the source file dependencies. So the source code allows building 200 files in parallel, it will launch 200 parallel jobs, which on a small laptop with just a few cores (say 4) might be an issue.

In practice, for me, `-j16` gives pretty much the most parallelism anyway, and it will not break machines with smaller number of cores.

**Comment by czgdp1807** [comment]
This can be closed I think? Manually specifying `-j8` or `-j5` or `-j16` should be fine. Using `-j` has the potential to stall someone's system.

**Comment by certik** [comment]
I think we can close it for now.

**Pull request closed without merging**
