### PR TITLE
[Draft] Add str to visit_ListItem

### PR DESCRIPTION
**Pull request by Abdelrahman-Kh-Fouad**

### CODE REVIEW

**Comment by namannimmo10** [comment]
Can you add some tests?

**Comment by Abdelrahman-Kh-Fouad** [comment]
> Can you add some tests?

visit_listItem doesn't work with strings so, i will try to figure out where is the problem and fix it, then i will add some tests.

**Comment by czgdp1807** [comment]
Please merge main into your branch. Lists are now completely implemented in LLVM.

**Comment by namannimmo10** [comment]
I think this PR can be closed. Thanks, @Abdelrahman-Kh-Fouad for giving this a try.

**Pull request closed without merging**
