### PR TITLE
Implement `visit_Assert` codegen for cpp

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Review by namannimmo10 — APPROVED** [review]
Looks great, thanks!

**Comment by certik** [comment]
I think you have to also include `cassert`, according to: https://en.cppreference.com/w/cpp/error/assert

**Review by certik — APPROVED** [review]
I think that will work. Did you test if it compiles? If it does, then you can merge it after tests pass.

**Comment by certik** [comment]
I guess you should merge the latest main and regenerate tests.

**Comment by Smit-create** [comment]
Thanks for the reviews. Merging!!

**Pull request merged**
