### PR TITLE
Added struct test

### PR DESCRIPTION
**Pull request by ronnuriel**
Another simple struct test to get a better understanding how to work with inner structs 
* Note: llvm failed

### CODE REVIEW

**Comment by Smit-create** [comment]
Thanks, @ronnuriel. I think your test works on PR #2056

**Comment by ronnuriel** [comment]
Do you want me the check and create another commit?

**Comment by Smit-create** [comment]
I already have added a test in #2056

**Comment by Smit-create** [comment]
@ronnuriel This can be closed as #2056 is merged. Thanks for the PR.

**Pull request closed without merging**
