### PR TITLE
CI: testing an even older commit

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
I am slightly confused. How are we testing an older commit? I could not see any file changes in this PR.

**Comment by certik** [comment]
So it passed here. I am rerunning the macOS job again. I'll run it at least 5 times and see if I can trigger the hang. If not, then this commit might work. Then we just need to bisect it.

**Comment by anutosh491** [comment]
Okay I see the CI passes here. What does this tell us though ? And how do we reset to this commit !

**Comment by certik** [comment]
Restarted again, running for the 3rd time. We want to be 100% sure it works.

This PR is testing the commit a5e3d042f1dea0d49c65ab933eaff086b9a66683.

Assuming this commit works, then we just have to bisect until we find the problem. I suspect it could be some segfault in the symbolic support?

**Comment by certik** [comment]
It looks like it is hanging now... So event his old commit fails.

**Comment by certik** [comment]
We need to go deeper: https://github.com/lcompilers/lpython/pull/2516.

**Pull request closed without merging**
