### PR TITLE
[ASR Pass] Symbolic: Simplify the symbolic handling

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
This PR is Ready for Review!
There is still more scope for simplification.
Let's merge this and then work on the remaining simplifications.

**Review by certik — APPROVED** [review]
It removes a lot of code and tests pass, so from this perspective it's great.

I didn't review the details of the changes in `replace_symbolic.cpp` much.

@anutosh491 can you please review this?

**Review by anutosh491 — APPROVED** [review]
I went through the changes commit by commit and I think pass is correctly structured and better aligned now. Thanks for the refactoring !

**Comment by Thirumalai-Shaktivel** [comment]
Cool, thanks for the reviews!

**Pull request merged**
