### PR TITLE
Implemented Str.Count() method

### PR DESCRIPTION
**Pull request by SudhanshuJoshi09**
1. Implemented Str.Count() method
2. Included tests for validating str.count.

### CODE REVIEW

**Review by Thirumalai-Shaktivel — APPROVED** [review]
This could have been implemented in IntrinsicFunction. 
But this is fine for now, I think.

Looks good, thank you!

**Review by anutosh491 — APPROVED** [review]
looks good !

**Comment by certik** [comment]
Thanks!

**Comment by OculusMode** [comment]
Small nitpicking on this but why to use an algorithm having O(n * m), we do have algos like boyer-moore, or even rabin karp if we do not wish to eat space.

some ref for this: https://en.wikipedia.org/wiki/String-searching_algorithm

**Comment by certik** [comment]
@OculusMode awesome, thanks! Can you post your comment as a new issue?

Then we can send PRs to implement it. If you are interested in this, that would be great.

**Comment by OculusMode** [comment]
Sure, can do that.

**Pull request merged**
