### PR TITLE
CI: Enable LLVM and C backends on macOS

### PR DESCRIPTION
**Pull request by certik**
Towards #2520.

### CODE REVIEW

**Comment by certik** [comment]
1st time it passed, trying 2nd time.

**Comment by certik** [comment]
2nd passed, trying 3rd time.

**Comment by certik** [comment]
Passed. Trying 4th time.

**Comment by certik** [comment]
Passed. Trying 5th time.

**Comment by anutosh491** [comment]
I think the checks pass this time too !

**Comment by certik** [comment]
I think it works!

It was the `-j16` that fails on macOS at the CI. Just doing `-j1` fixes everything.

**Comment by anutosh491** [comment]
Thanks for fixing this !

**Pull request merged**
