### PR TITLE
Modification for ASR support of array type with size()

### PR DESCRIPTION
**Pull request by ansharlubis**
Modified the `visit_Call` in `SymbolTableVisitor` so that the following function can compile to ASR, but still not to LLVM.
```` python
def f(a: f64[:], b: f64[:]) -> f64[size(a)]:
    r: f64[size(a)]
    i: i32
    for i in range(size(a)):
        r[i] = a[i] + b[i]
    return r
````

### CODE REVIEW

**Comment by certik** [comment]
Great idea, I think we should allow this. This example is not generic, and it must generate roughly equivalent to the following code which works:
```python
from ltypes import f64, TypeVar

n = TypeVar("n")
def f(n: i32, a: f64[n], b: f64[n]) -> f64[n]:
    r: f64[size(a)]
    i: i32
    for i in range(size(a)):
        r[i] = a[i] + b[i]
    return r

def main():
    a: f64[1] = empty(1)
    b: f64[1] = empty(1)
    c: f64[1] = empty(1)
    c = f(1, a, b)
```

LFortran ca compile this:
```fortran
program test

real :: x(1), y(1), z(1)

z = f(x, y)

contains

function f(a, b) result(r)
real, intent(in) :: a(:), b(:)
!real :: r(size(a))
real :: r(1)
integer :: i
do i = 1, size(a)
    r(i) = a(i) + b(i)
end do
end function

end program
```
But not this yet:
```
program test

real :: x(1), y(1), z(1)

z = f(x, y)

contains

function f(a, b) result(r)
real, intent(in) :: a(:), b(:)
real :: r(size(a))
integer :: i
do i = 1, size(a)
    r(i) = a(i) + b(i)
end do
end function

end program
```
Which gives an error message:
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1726
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 743
    res = fe.get_llvm3(*asr, lpm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 318
    compiler_options.platform, run_fn);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5699
    pass_manager.apply_passes(al, &asr, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 172
    _apply_passes(al, asr, _passes, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 85
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 423
    LFORTRAN_ASSERT(asr_verify(unit));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 521
    v.visit_TranslationUnit(unit);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 110
    for (auto &a : x.m_global_scope->get_scope()) {
  File "../libasr/asr.h", line 3799
  File "../libasr/asr.h", line 3572
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 145
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 3799
  File "../libasr/asr.h", line 3573
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 247
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 3799
  File "../libasr/asr.h", line 3578
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 298
    visit_ttype(*x.m_type);
  File "../libasr/asr.h", line 3927
  File "../libasr/asr.h", line 3718
  File "../libasr/asr.h", line 4833
  File "../libasr/asr.h", line 4899
  File "../libasr/asr.h", line 3855
  File "../libasr/asr.h", line 3686
  File "../libasr/asr.h", line 4658
  File "../libasr/asr.h", line 3855
  File "../libasr/asr.h", line 3682
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 337
    require(symtab_in_scope(current_symtab, x.m_v),
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_verify.cpp", line 49
    throw LCompilersException("ASR verify failed: " + error_msg);
LCompilersException: ASR verify failed: Var::m_v `a` cannot point outside of its symbol table
```
So I would fix LFortran first, as it's really close to get this working. Make sure ASR and verify and LLVM can handle this. Then update LPython to do the same.

**Comment by certik** [comment]
Please open up an issue at LFortran with the above, let's get it fixed.

**Comment by ansharlubis** [comment]
@certik I haven't joined the LFortran gitlab yet, can I just post an issue without any credential?

**Comment by certik** [comment]
@ansharlubis we moved to github, just open up an issue here: https://github.com/lfortran/lfortran/issues

**Comment by ansharlubis** [comment]
Then, I will close this pull request for now.

**Pull request closed without merging**
