### PR TITLE
Initial PythonCallable implementation

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**
Towards: https://github.com/lcompilers/lpython/issues/703

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
We need to handle the array as a return variable.

**Comment by Thirumalai-Shaktivel** [comment]
@certik Am I in the right direction?

**Comment by certik** [comment]
I would take this:
```
@pythoncallable
def fast_sum(n: i32, x: f64[:]) -> f64:
    s: f64 = 0.0
    i: i32
    for i in range(n):
        s += x[i]
    return s
```
and produce just one function in C:
```
static PyObject* fast_sum(PyObject* n, PyObject* x) {
// convert n from Python to LPython
// convert x from Python/NumPy array to LPython descriptor
// Now we emit code for
/*
    s: f64 = 0.0
    i: i32
    for i in range(n):
        s += x[i]
*/
// Here we convert s: f64 to CPython PyObject and return it correctly
//    return s
}
```

**Comment by Thirumalai-Shaktivel** [comment]
```c

// Implementations
double fast_sum(int32_t n, struct r64* x, struct r64* y)
{
    int32_t __1_k;
    double _lpython_return_variable;
    int32_t i;
    double s;
    s =   0.00000000000000000e+00;
    for (i=0; i<=n - 1; i++) {
        s = s + x->data[(i - x->dims[0].lower_bound)];
    }
    for (__1_k=((int32_t)y->dims[1-1].lower_bound); __1_k<=((int32_t) y->dims[1-1].length + y->dims[1-1].lower_bound - 1); __1_k++) {
        printf("%lf%s", y->data[(__1_k - y->dims[0].lower_bound)], " ");
    }
    printf("%s", "\b");
    printf("\n");
    _lpython_return_variable = s;
    return _lpython_return_variable;
}

// Define the Python module and method mappings
static PyObject* fast_sum_define_module(PyObject* self, PyObject* args) {
    // Initialize NumPy
    import_array();

    // Declare arguments and return variable
    int32_t n;
    PyArrayObject *x;
    PyArrayObject *y;
    double _lpython_return_variable;

    // Parse the arguments from Python
    if (!PyArg_ParseTuple(args, "iOO", &n, &x, &y)) {
        PyErr_SetString(PyExc_TypeError, "An error occurred in the `lpython` decorator: "
            "Failed to parse or receive arguments from Python");
        return NULL;
    }

    // fill array details for x
    if (PyArray_NDIM(x) != 1) {
        PyErr_SetString(PyExc_TypeError, "An error occurred in the `lpython` decorator: "
            "Only 1 dimension array is supported for now.");
        return NULL;
    }

    struct r64 *s_array_x = malloc(sizeof(struct r64));
    {
        double *array;
        // Create C arrays from numpy objects:
        PyArray_Descr *descr = PyArray_DescrFromType(PyArray_TYPE(x));
        npy_intp dims[1];
        if (PyArray_AsCArray((PyObject **)&x, (void *)&array, dims, 1, descr) < 0) {
            PyErr_SetString(PyExc_TypeError, "An error occurred in the `lpython` decorator: "
                "Failed to create a C array");
            return NULL;
        }

        s_array_x->data = array;
        s_array_x->n_dims = 1;
        s_array_x->dims[0].lower_bound = 0;
        s_array_x->dims[0].length = dims[0];
        s_array_x->is_allocated = false;
    }


    // fill array details for y
    if (PyArray_NDIM(y) != 1) {
        PyErr_SetString(PyExc_TypeError, "An error occurred in the `lpython` decorator: "
            "Only 1 dimension array is supported for now.");
        return NULL;
    }

    struct r64 *s_array_y = malloc(sizeof(struct r64));
    {
        double *array;
        // Create C arrays from numpy objects:
        PyArray_Descr *descr = PyArray_DescrFromType(PyArray_TYPE(y));
        npy_intp dims[1];
        if (PyArray_AsCArray((PyObject **)&y, (void *)&array, dims, 1, descr) < 0) {
            PyErr_SetString(PyExc_TypeError, "An error occurred in the `lpython` decorator: "
                "Failed to create a C array");
            return NULL;
        }

        s_array_y->data = array;
        s_array_y->n_dims = 1;
        s_array_y->dims[0].lower_bound = 0;
        s_array_y->dims[0].length = dims[0];
        s_array_y->is_allocated = false;
    }

    // Call the C function
    _lpython_return_variable = fast_sum(n, s_array_x, s_array_y);

    // Build and return the result as a Python object
    return Py_BuildValue("d", _lpython_return_variable);
}

// Define the module's method table
static PyMethodDef fast_sum_module_methods[] = {
    {"fast_sum", fast_sum_define_module, METH_VARARGS,
        "Handle arguments & return variable and call the function"},
    {NULL, NULL, 0, NULL}
};

// Define the module initialization function
static struct PyModuleDef fast_sum_module_def = {
    PyModuleDef_HEAD_INIT,
    "lpython_module_fast_sum",
    "Shared library to use LPython generated functions",
    -1,
    fast_sum_module_methods
};

PyMODINIT_FUNC PyInit_lpython_module_fast_sum(void) {
    PyObject* module;

    // Create the module object
    module = PyModule_Create(&fast_sum_module_def);
    if (!module) {
        return NULL;
    }

    return module;
}
```

**Comment by certik** [comment]
Later, the `pythoncallable` decorator can take the decorated `fast_sum` function and keep it as `internal_fast_sum`. Then create a new `fast_sum` function that is roughly equivalent to:
```
fast_sum(n, x, y) {
    return internal_fast_sum(CastPythonToLPython(n), CastPythonToLPython(x), CastPythonToLPython(y));
}
```
This will be in ASR, so the arguments "x" will be BindPython in fast_sum, but LPython in internal_fast_sum.

**Comment by Thirumalai-Shaktivel** [comment]
Ready for review!

**Comment by Thirumalai-Shaktivel** [comment]
Yup, this is ready for final review and merge!

**Comment by Thirumalai-Shaktivel** [comment]
I will merge this and add more tests in a separate PR!
Thanks for the review!

**Comment by Thirumalai-Shaktivel** [comment]
The changes in the PR: https://github.com/lcompilers/lpython/pull/2012, alter the return type handling. So the seg fault. I will look into it and report back.

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lcompilers/lpython/blob/c459bb538801d9db8b70e5f0d13984ae866f60cc/src/libasr/pass/pass_utils.h#L670-L672

Maybe you could change the above as follows:

```bash
if (ASRUtils::get_FunctionType(x)->m_abi == ASR::abiType::BindPython
    && ASRUtils::get_FunctionType(x)->m_deftype == ASR::deftypeType::Interface) { 
    return; 
}
```
I guess it might fix the issue you are facing.

**Comment by Thirumalai-Shaktivel** [comment]
Ready

**Comment by Thirumalai-Shaktivel** [comment]
Thank you @Shaikh-Ubaid, but I modified the code to use your changes!
The changes were very useful, it reduces unwanted operations to handle array return type.

**Review by certik — APPROVED** [review]
I think this looks great.

Right now we use the C backend anyway, so this PR is an improvement.

To later use the LLVM backend, I think we need to refactor this into an ASR->ASR pass, see https://github.com/lcompilers/lpython/issues/1996 for details. This PR is the first step towards this (it moves the Python C/API logic from lpython.py into the C backend). The next step will be to lift it from the C backend into an ASR->ASR pass. Then LLVM should work out of the box.

**Pull request merged**
