### PR TITLE
List in C/C++ backend

### PR DESCRIPTION
**Pull request by czgdp1807**
Implementing 2.ii in https://github.com/lcompilers/lpython/issues/1077#issuecomment-1236134901.

Closes https://github.com/lcompilers/lpython/issues/1077

Benchmark - https://github.com/lcompilers/lpython/issues/857#issuecomment-1200960150 (see `list04` row). Our generated C code (with no optimisation flags enabled for C compiler) is faster than un-optimised (no -O3 flag) executable generated `clang++`.

### CODE REVIEW

**Comment by czgdp1807** [comment]
@certik This is ready to review. Feel free to review the diff in total and let me know if any change is to be made. Otherwise I will clean up the git history and merge.

**Review by certik — APPROVED** [review]
Thanks for implementing it!

I think this is fine to merge.

As an improvement in subsequent PRs, the C++ version should just use `std::vector` for lists, as that is the natural data structure that people would use in C++, pretty much equivalent to our list in ASR.

**Comment by czgdp1807** [comment]
> As an improvement in subsequent PRs, the C++ version should just use `std::vector` for lists, as that is the natural data structure that people would use in C++, pretty much equivalent to our list in ASR.

I think we should expose this with something like `--use-stl` for C++ backend. The scene is that our implementation is very competitive and light weight (no templates because we already know the types so we directly create the correctly typed lists and hence we don't depend on templating support of C++). So, it should be left to the user to decide whether they want to use our implementations for container data structures or STL implementations.

**Comment by certik** [comment]
Yes, making it configurable is even better.

**Comment by certik** [comment]
How do the list benchmarks behave? Are we now getting the same performance in C/C++ as in LLVM, and if not, why not?

**Comment by czgdp1807** [comment]
I don’t know how to enable -O3 optimisation for C compiler in integration tests. Please let me know and I will share the benchmark data with you.

**Comment by certik** [comment]
I would execute the benchmarks by hand. Just compile it by hand and enable all optimization options.

**Pull request merged**
