### PR TITLE
Strings methods: `swapcase()`

### PR DESCRIPTION
**Pull request by Abdelrahman-Kh-Fouad**

### CODE REVIEW

**Comment by Abdelrahman-Kh-Fouad** [comment]
Ready for review @certik @czgdp1807

**Review by certik — APPROVED** [review]
I think this looks good. Thanks!

**Comment by certik** [comment]
I resolved the conflicts.

**Review by czgdp1807 — COMMENTED** [review]
I think this looks good. Just clean up the git history and make sure there aren't any build warnings.

**Comment by Abdelrahman-Kh-Fouad** [comment]
> I think this looks good. Just clean up the git history and make sure there aren't any build warnings.

i already rebased the branch before i open the pr, i'm sure there aren't build warnnings.

**Comment by czgdp1807** [comment]
> i already rebased the branch before i open the pr, i'm sure there aren't build warnnings.

That's fine. I see a merge commit in the history of this PR. You can clean up the git history by following the steps in the link https://github.com/lcompilers/lpython/blob/main/doc/src/rebasing.md#merging

**Comment by Abdelrahman-Kh-Fouad** [comment]
@czgdp1807  Done!

**Comment by czgdp1807** [comment]
Conflicts to be resolved. Actually your string PRs depend on each other, so after merging one others will face conflicts. Resolve conflicts here, clean up the git history then will merge this. Same for your other PR.

**Comment by czgdp1807** [comment]
@Abdelrahman-Kh-Fouad Fix the conflicts here please.

**Comment by Abdelrahman-Kh-Fouad** [comment]
done! @czgdp1807

**Pull request merged**
