### PR TITLE
Adding dependencies in `StructType`, `UnionType` and `EnumType`

### PR DESCRIPTION
**Pull request by czgdp1807**

### CODE REVIEW

**Comment by czgdp1807** [comment]
@certik This is ready. I will add dependencies for Variable symbol later. For now dependencies in aggregate types is the immediate requirement.

**Review by certik — APPROVED** [review]
The PR looks good. I can see you construct the dependencies and check them in verify.

But I don't see you using the dependencies in the LLVM backend -- is it not needed there? I can see you are using them in the C backend.

**Comment by czgdp1807** [comment]
> But I don't see you using the dependencies in the LLVM backend -- is it not needed there

I think so. The test I added works fine in LLVM already. C backend needs those dependencies because the order of declaration matters there.

**Comment by certik** [comment]
Makes sense.

**Pull request merged**
