### PR TITLE
Use expr instead of symbol in new added ASR nodes

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
@certik Any views on how to move forward with this?

**Comment by certik** [comment]
Just do one ASR node change at a time, and fix up the AST->ASR to compile. I don't think there is any fundamental issue. If there is, you can describe the issue here and let's have a look.

**Comment by namannimmo10** [comment]
Thanks for working on this, Smit.

**Review by certik — COMMENTED** [review]
I think this looks good, thanks Smit and Naman! In future PRs, let's also add tests for this, such as `(a+b)[3]` for lists.

**Comment by Smit-create** [comment]
Thanks! I would still recommend avoiding `Merge main` commits that unnecessarily populate git history, instead use rebase and force push.

**Comment by certik** [comment]
I agree. Only merge main into a PR if it is a difficult PR that would be hard to rebase, usually for a big PR. Or if we want to preserve test commits, if it was very hard to get things passing. For simple PRs like this one we should always rebase, as it is cleaner.

**Pull request merged**
