### PR TITLE
Overload all existing built-in functions

### PR DESCRIPTION
**Pull request by namannimmo10**
- [x]  overload `abs`
- [x] overload `round` 
- [x] overload `pow`

### CODE REVIEW

**Review by certik — APPROVED** [review]
I think this looks good! Very helpful, this makes the intrinsic functions pretty much usable now.

**Review by certik — APPROVED** [review]
I think that looks good.

I wonder what the purpose of the `pow` function is, when we have `**` in Python.

**Comment by namannimmo10** [comment]
Perhaps once we add support for the third (optional) argument in `pow`, it can more efficiently compute `a` to the power `b` modulo `c`, than `pow(a, b)%c`

Have you heard about aliasing and chunking? This Pytalk by Raymond is really good: https://www.youtube.com/watch?v=UANN2Eu6ZnM (start from 8:50)

**Comment by certik** [comment]
> Have you heard about aliasing and chunking?

Not using this name. How does it apply here in your opinion?

**Comment by namannimmo10** [comment]
> Chunking refers to the process of taking individual pieces of information and grouping them into larger units

I think the fact what Raymond wants to convey is that instead of doing computationally-expensive tasks repeatedly, we can have functions (that would do it efficiently), thereby reducing the "registers" and maintaining our cognitive capacity. I am sure he can explain it much better!

**Comment by certik** [comment]
Yes, you don't want to have too large loop body, otherwise you run out of registers. The compiler unrolling facility must unroll in order to vectorize well, but not too much to run our of registers. Regarding using functions to structure your code, that seems obvious. I don't now how it applies to this PR though. :)

**Pull request merged**
