### PR TITLE
Handle doc string inside Class

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lcompilers/lpython/issues/1924

### CODE REVIEW

**Review by certik — APPROVED** [review]
Perfect, thanks!

**Comment by rebcabin** [comment]
Hi Ubaid -- would you be so kind as to give me the exact `git` command that I need to merge these updates into my remote branch? I currently work in remote `brian` and branch `brian-lasr`. My remote branch started life as a `fork` of `lcompilers/lpython`, but I don't know enough `git` to update my remote branch. I'm sure it's easy and probably everyone does it all the time, I just don't know the command.

**Comment by certik** [comment]
Try this:
```
git checkout master
git pull origin master
git checkout brian-lasr
git merge master
```

**Comment by rebcabin** [comment]
that might do it (with "main" instead of "master"). Thanks.

**Comment by rebcabin** [comment]
Actually looks like I should do it with GUI on GitHub. See "sync fork"
below. "Fork" seems a GitHub concept, not a git concept. Seems git's
concept is a remote. But this GUI thing might be more reliable.

[image: image.png]

**Comment by Shaikh-Ubaid** [comment]
>Actually looks like I should do it with GUI on GitHub. 

Yes, both the approaches work. As Dr. Ondrej shared, one can update the local repo with 

```
// first commit/save the current changes (if any)
...
git checkout main
git pull origin main
git checkout brian-lasr
git merge main // I usually use here `git rebase main`. In either case (rebase or merge), we might need to resolve conflicts (if any)
// Now brian-lasr is updated and one can continue working on it
...
// We commit the changes after work completion
...
// Now to update the brian-lasr branch at the remote `brian` repo (fork of lpython) one can do
git push brian brian-lasr // We need to use `git push brian brian-lasr -f` if we rebased in place of merging above
```

As you shared, you can also use the `sync fork` option. In this case I think one would do
```
// Click the button sync fork (on GitHub UI) for branch `brian-lasr` (I am unsure what the UI would do if there are conflicts)
...
// Now we need to update the local repo
// first commit/save the current changes  (if any)
git checkout brian-lasr // if not already checked out
git pull brian brian-lasr --rebase
// Now brian-lasr is updated and one can continue working on it
...
// We commit the changes after work completion
...
// Now to update the brian-lasr branch at the remote `brian` repo (fork of lpython) one can do
git push brian brian-lasr
```
Note that in the first approach your local `main` branch was also updated. In the second approach only the branch `brian-lasr` on your local copy is updated. One needs to manually update the local `main` branch. To do so, you can do
```
// first commit/save the current changes  (if any)
git checkout main
git pull origin main
```
(Updated local `main` branch is needed/useful so that later when we create a new branch from the `main` branch, we are sure that we are working with the latest changes.)

**Pull request merged**
