### PR TITLE
refactor: check for dependency only in parent scope

### PR DESCRIPTION
**Pull request by arteevraina**
Resolves: https://github.com/lcompilers/lpython/issues/2392

### CODE REVIEW

**Comment by certik** [comment]
@arteevraina This looks good. Can you send this PR against LFortran too, to ensure everything works there? After that we can merge.

**Comment by arteevraina** [comment]
> @arteevraina This looks good. Can you send this PR against LFortran too, to ensure everything works there? After that we can merge.

Sure.

**Comment by certik** [comment]
Let's merge the LFortran first, then we can merge this one. For LFortran, see here: https://github.com/lfortran/lfortran/pull/2798#discussion_r1382478397.

**Comment by arteevraina** [comment]
@certik Can we merge this as well ?

**Comment by certik** [comment]
Yes, I think this is good, thanks!

**Pull request merged**
