### PR TITLE
libasr: Add C backend Codegeneration using `--show-c`

### PR DESCRIPTION
**Pull request by Smit-create**
#393

### CODE REVIEW

**Comment by certik** [comment]
Thanks for the PR. Isn't most of the C backend almost identical to the C++ backend? As mentioned in #393, I would prefer to have just one file, say `asr_to_cpp.cpp`, and in there have some flags to determine the kind of output. It seems to me it should be doable, because:

* We want to be able to configure how exactly the C++ is generated, things like:
    * arrays (C style, Kokkos, XTensor, ...)
    * strings (C style, std::string)
    * list (std::vector, our custom C approach)
* C that we would generate is a subset of C++, it seems it's effectively just one of the options above, and we have to have such options anyway

I think we just have to decide how types are being translated, and we have to support multiple C++ implementations of arrays, so we just add a C version.

The general syntax for functions, expressions, etc. is I think almost the same.

**Comment by Smit-create** [comment]
Yeah, that's true. Maybe we can add a class called `ASRtoC` and `ASRtoCPP` as the child class of `ASRtoC` which will add/override the methods of its parent class?

**Review by certik — APPROVED** [review]
This is probably fine. We will then create a common base visitor and put all the identical visitor functions as well as any other common code that is shared with the C++ backend in there. This approach allows us to work on the two backends separately, and keep the code reasonably simple. And we can always add methods to the base class that internally dispatch on C/C++, if that is easier. So it seems this is the best of all approaches.

**Comment by certik** [comment]
Simplified in #517.

**Pull request merged**
