### PR TITLE
Added support for Out[S]

### PR DESCRIPTION
**Pull request by anutosh491**
Thanks to the well framed `subroutine_from_function` pass. Now we can return symbolic objects through a cummulative result of the `subroutine_from_function` and `symbolic` pass.

### CODE REVIEW

**Comment by anutosh491** [comment]
I think the `subroutine_from_function` pass is aligned before the `symbolic` pass so we don't need to alter that!

**Comment by anutosh491** [comment]
So currently we can do something like 
```
(lf) anutosh491@spbhat68:~/lpython/lpython$ cat examples/expr2.py 
from lpython import S
from sympy import pi, Symbol

def func() -> S:
    print(Symbol("x"))
    return pi

def test_func():
    z: S = func()
    print(z)

test_func()
```
```
(lf) anutosh491@spbhat68:~/lpython/lpython$ lpython --enable-symengine --backend=c examples/expr2.py 
x
pi
```
But through the llvm backend we would still be stuck as we had discussed previously (https://github.com/lcompilers/lpython/issues/2411#issuecomment-1806738228)
```
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
void** %_lpython_return_variable
 void*  call void @basic_const_pi(void** %_lpython_return_variable)
Call parameter type does not match function signature!
  %4 = load void*, void** %__libasr__created__var__0__func_call_res, align 8
 void**  call void @__module___main___func(void* %4)
 ```

**Comment by certik** [comment]
I think this is good. Can you please add a test?

Also, can you submit just the libasr change to lfortran, to ensure everything works there?

**Comment by anutosh491** [comment]
> I think this is good. Can you please add a test?
Also, can you submit just the libasr change to lfortran, to ensure everything works there?

Done.

**Comment by anutosh491** [comment]
We should also discuss as to how we would address comment (https://github.com/lcompilers/lpython/issues/2411#issuecomment-1806738228) because if you think about it, the function definition for `mrv` would look like the following 

```
def mrv(e: S, x: S) -> tuple[dict[S, S], S]:
```
Trying to replicate something like the following 
```
>>> from sympy.series.gruntz import mrv
>>> mrv(exp(x), x)
({exp(x): _Dummy_40}, {}, _Dummy_40)
```
Which means we need to return a `tuple` with a `dict` inside it and dictionaries aren't currently supported through the `C` backend, so untill we get the `llvm` backend working, we might be blocked.

**Review by certik — APPROVED** [review]
I think that's fine. Can you also add a test for `Out[S]` explicitly? Right now it is only tested implicitly via the subroutine_from_function.

**Comment by anutosh491** [comment]
> Can you also add a test for Out[S] explicitly?

Sure.

**Pull request merged**
