### PR TITLE
Initial support for callbacks

### LINKED ISSUE #1608: Supporting Callbacks in LPython
For providing functionalities like: https://github.com/lcompilers/lpython/issues/992#issuecomment-1478215958 we need to support callbacks. A simple example is:
```python
from ltypes import i32, Callable

def f(x: i32) -> i32:
    return x + 1

def g(func: Callable[[i32], i32], arg: i32):
    ret: i32
    ret = func(arg)
    print(ret)

g(f, 10)
```

Currently, this throws the following error:
<details>
<summary> Error </summary>
<p>

```console
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/thebigbool/repos/lpython/src/bin/lpython.cpp", line 1602
    return emit_asr(arg_file, lpython_pass_manager, runtime_library_dir,
  File "/Users/thebigbool/repos/lpython/src/bin/lpython.cpp", line 194
    r = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics,
  File "/Users/thebigbool/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 6237
    if (res.ok) {
  File "/Users/thebigbool/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3814
    v.visit_Module(ast);
  File "/Users/thebigbool/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3302
    visit_stmt(*x.m_body[i]);
  File "/Users/thebigbool/repos/lpython/src/lpython/python_ast.h", line 1882
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/thebigbool/repos/lpython/src/lpython/python_ast.h", line 1750
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/Users/thebigbool/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3389
    ASR::ttype_t *arg_type = ast_expr_to_asr_type(x.base.base.loc, *x.m_args.m_args[i].m_annotation);
  File "/Users/thebigbool/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1540
    this->visit_expr(*s->m_slice);
  File "/Users/thebigbool/repos/lpython/src/lpython/python_ast.h", line 1909
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/thebigbool/repos/lpython/src/lpython/python_ast.h", line 1815
    case exprType::Tuple: { v.visit_Tuple((const Tuple_t &)x); return; }
  File "/Users/thebigbool/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2674
    this->visit_expr(*x.m_elts[i]);
  File "/Users/thebigbool/repos/lpython/src/lpython/python_ast.h", line 1909
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/thebigbool/repos/lpython/src/lpython/python_ast.h", line 1814
    case exprType::List: { v.visit_List((const List_t &)x); return; }
  File "/Users/thebigbool/repos/lpython/src/lpython/python_ast.h", line 1941
    void visit_List(const List_t & /* x */) { throw LCompilersException("visit_List() not implemented"); }
LCompilersException: visit_List() not implemented
```
</p>
</details>

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #1608

### CODE REVIEW

**Comment by certik** [comment]
Something like that. I am refactoring the callbacks right now in LFortran. In LFortran, we either specify the function argument to be a Function symbol (instead of a Variable), or use a Variable, see https://github.com/lfortran/lfortran/pull/1578 for a roadmap.

For now I think this PR is fine.

**Comment by Smit-create** [comment]
> we either specify the function argument to be a Function symbol (instead of a Variable)

Yep, I have done the same thing in this PR. As in Fortran, we have an `interface`, for Python, whenever there's a function as a parameter, I create an empty callback function symbol in the scope of the parent function that works the same way as we do in the Fortran interface.

**Review by certik — APPROVED** [review]
I think that this is fine. Note that we have greatly improved the callbacks in LFortran just yesterday. After merging, do you think you could please sync LFortran/LPython on this?

Another issue: in LFortran we currently allow two ways to do callbacks:

* Var points to Function directly
* Var points to Variable, which points to FunctionType and Function

The second approach I think is more natural and versatile, so we should use it. That requires to sync LFortran's improvements here.

So to move forward, I suggest we merge this, then sync, and then rework it, maybe in few weeks after we harden the new approach in LFortran more.

**Comment by Smit-create** [comment]
Sure, would rework this once we sync `libasr`. Thanks!

**Pull request merged**
