### PR TITLE
Supporting lists of strings

### PR DESCRIPTION
**Pull request by czgdp1807**

### CODE REVIEW

**Comment by certik** [comment]
Perfect! This one is very important. Once this works, we'll be able to implement many standard library functions.

**Comment by czgdp1807** [comment]
I will complete it either tomorrow or on Monday.

**Comment by czgdp1807** [comment]
@certik This is ready. Let me know if you think anything should be changed here. Otherwise I will clean up the git history.

**Review by certik — APPROVED** [review]
I think this looks great!

**Comment by czgdp1807** [comment]
In future if you face any bugs with lists, let me know. For now things work (hopefully).

**Comment by certik** [comment]
> In future if you face any bugs with lists, let me know. For now things work (hopefully).

Sure, here is one: https://github.com/lcompilers/lpython/issues/859 :)

**Pull request merged**
