### PR TITLE
Use add_or_overwrite_symbol

### LINKED ISSUE #1875: Tests fail locally
See https://lfortran.zulipchat.com/#narrow/stream/311866-LPython/topic/Integration.20Tests

### PR DESCRIPTION
**Pull request by certik**
Fixes #1875.

### CODE REVIEW

**Comment by certik** [comment]
However often times using this function means there is a bug somewhere. Is replacing the older symbol intended here? We would need to investigate.

**Comment by certik** [comment]
The other question is why this didn't trigger at the CI. Either it only happens on M1, or the assertions don't trigger at the CI.

**Comment by certik** [comment]
I think we never test in Debug mode.

**Comment by Shaikh-Ubaid** [comment]
>The other question is why this didn't trigger at the CI. Either it only happens on M1, or the assertions don't trigger at the CI.
>I think we never test in Debug mode.

Yes, we test release mode at the CI. In release mode, assertions are disabled and I think hence, this passes at the CI.

**Pull request merged**
