### PR TITLE
Initial support for `dict` data structure

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lcompilers/lpython/issues/964

Following is the plan,

1. Represent `dict` with the help of a struct in LLVM. Maintain original key-value pairs for the purpose of collision handling and in case a collision happens then distinguishing between update and insert operation. We need original key-value pairs anyways for all kinds of collision handling strategy.
2. If collision happens while insertion then do [linear probing](https://web.stanford.edu/class/archive/cs/cs166/cs166.1166/lectures/12/Small12.pdf) (simple as well as cache efficient).
3. Resizing strategy - [All-at-once resizing strategy](https://en.wikipedia.org/wiki/Hash_table#Resizing_by_moving_all_entries). Will happen if load factor touches a threshold value. Simpler than lazy resizing in which don't copy all the older key-value pairs into new array but instead only when they are accessed. Its a bit complicated to implement so I will do it in future.

TODOs after this PR - https://github.com/lcompilers/lpython/issues/983#issuecomment-1218136744

### CODE REVIEW

**Comment by czgdp1807** [comment]
@certik This is ready for review. I have mentioned my TODOs after this PR in https://github.com/lcompilers/lpython/issues/983#issuecomment-1218136744. You can review each commit individually if you want. Let me know if anything needs a change here.

**Review by certik — APPROVED** [review]
I reviewed every commit, everything looks great.

My only possible question is if the CPython version of the test takes a long time, if so, we should reduce the number of loop iterations in the test. 

That can be adjusted later.

So +1 to merge.

Great job!

**Comment by certik** [comment]
@czgdp1807 is this ordered or unordered dictionary?

**Comment by czgdp1807** [comment]
I think this is unordered dictionary (because hash maps are unordered in nature). For ordered dictionary we will require an implementation similar to std::map.

**Comment by certik** [comment]
Here is another way to implement OrderedDict: https://github.com/Aqcurate/OrderedDict#ordered-dictionary-implementation

**Pull request merged**
