### PR TITLE
Declare variables on the same line

### PR DESCRIPTION
**Pull request by certik**
This is the most natural Python syntax to declare variables on the same
line.

### CODE REVIEW

**Review by czgdp1807 — APPROVED** [review]
This is cool.

**Comment by czgdp1807** [comment]
I think we can merge this?

**Comment by certik** [comment]
Sure. I think this is good enough. It's slightly annoying to do `x: i32; y: i32; z: i32` instead of `x, y, z: i32`, but the Python syntax does not allow it. And doing  something like `i32("x y z")` seems not worth it. I think the above is good enough for now.

**Comment by czgdp1807** [comment]
Yeah at least every declaration stays in the same line.

**Pull request merged**
