### PR TITLE
Disable implicit casting by default and implement intrinsic functions for casting

### PR DESCRIPTION
**Pull request by akshanshbhatt**
Todo:
- [ ] Implement intrinsic functions for manual casting (`i32(x)`, `i64(x)`, `f32(x)`, `f64(x)`).
- [ ] Update tests accordingly.
- [ ] ~Add `--allow-implicit-casting` compiler flag (https://github.com/lcompilers/lpython/issues/1006#issuecomment-1242232388).~

As of now, the example in https://github.com/lcompilers/lpython/issues/1142 gives the output as we expected -

```py
❯ bat examples/expr2.py
───────┬─────────────────────────────────────────────────────────────
       │ File: examples/expr2.py
───────┼─────────────────────────────────────────────────────────────
   1 + │ from ltypes import i32
   2 + │
   3   │ def main0():
   4   │     x: i32
   5 ~ │     x = 1/2
   6   │     print(x)
   7   │
   8 ~ │ main0()
───────┴─────────────────────────────────────────────────────────────
❯ lpy --show-asr examples/expr2.py
semantic error: Type mismatch in assignment, the types must be compatible
 --> examples/expr2.py:5:5
  |
5 |     x = 1/2
  |     ^   ^^^ type mismatch ('i32' and 'f64')


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

### CODE REVIEW

**Comment by certik** [comment]
Thanks for working on this! This was on my TODO list, I think we want to do this change soon, since it's a breaking change.

**Comment by certik** [comment]
We don't need to add the compiler flag in this PR. If there is a need, we can add it later.

**Comment by akshanshbhatt** [comment]
@certik, The functions are mainly working fine. I have to work on the `BinOp` casting (for example - making `i32(3.2 + 1.5)` work) and a few other things before I can complete this PR. However, there are a few things where I need some help -

```py
$ cat examples/expr2.py
from ltypes import i32

def main0():
    x: f64
    x = i32(6.8)
    print(x)

main0()
$ lpython examples/expr2.py
semantic error: Type mismatch in assignment, the types must be compatible
 --> examples/expr2.py:5:5
  |
5 |     x = i32(6.8)
  |     ^       ^^^ type mismatch ('f64' and 'i32')


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

Here the error message should point to the complete `i32()` part but it instead, it just points to the argument passed. Ideally, it should be -

```py
  |
5 |     x = i32(6.8)
  |     ^   ^^^^^^^^ type mismatch ('f64' and 'i32')
```
How can I fix this?

**Comment by certik** [comment]
You have to pass in the location information of the `i32` node, not the argument `6.8`.

**Comment by czgdp1807** [comment]
Self-assigning. I will complete this tomorrow. Thanks.

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/lcompilers/lpython/pull/1271

**Comment by akshanshbhatt** [comment]
> Closing in favour of #1271

Thanks for working on this, @czgdp1807! I just saw your previous messages on this PR; sorry for that - I was busy with my midsemester exams.

**Pull request closed without merging**
