### PR TITLE
CI: Support integration_tests for X86 and WASM_X86 backends

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` adds support for `integration_tests` for the `x86` and `wasm_x86` backends. There is a basic test case `integration_tests/print_03.py` (which just prints an integer `5`) (temporarily) added to test if the generated `x86` binary executes.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Comment by Shaikh-Ubaid** [comment]
It seems the generated `x86` output file does not run on `Mac`, hence the `macos` `CI` test is failing, I think.

**Comment by Shaikh-Ubaid** [comment]
Only the latest `six` commits are part of this `PR`. The rest of the commits are part of https://github.com/lcompilers/lpython/pull/1265.

**Comment by Shaikh-Ubaid** [comment]
Also, we are executing the `integration_tests` for `x86` and `wasm_x86` backends only on `linux`. Respective commit [TEST: Execute integration_tests for x86 and wasm_x86 backends only on Linux](https://github.com/lcompilers/lpython/pull/1262/commits/06631264054a21518d344a4214dfa97b6f63f403).

**Comment by Smit-create** [comment]
We can wait on this till #1270 is merged so that we can re-use the code here.

**Review by certik — APPROVED** [review]

**Comment by Shaikh-Ubaid** [comment]
Rebased on top of latest main, resolved conflicts, adding it to auto-merge as it seems approved.

**Pull request merged**
